
project_id = "tfkchwuphjaauyfqptbk"

# Webhook Processor function config
[functions.webhook-processor]
verify_jwt = false

# Webhook Trigger function config
[functions.webhook-trigger]
verify_jwt = false

# Webhook Cron function config - scheduler requires no JWT
[functions.webhook-cron]
verify_jwt = false
