project_id = "tfkchwuphjaauyfqptbk"

# Auth configuration
[auth]
enabled = true
site_url = "https://clini.one"

# Email template configuration
[auth.email.template.recovery]
subject = "Redefinir sua senha - Clini.One"
content_path = "./supabase/templates/reset-password.html"

# Webhook Processor function config
[functions.webhook-processor]
verify_jwt = false

# Webhook Trigger function config
[functions.webhook-trigger]
verify_jwt = false

# Webhook Cron function config - scheduler requires no JWT
[functions.webhook-cron]
verify_jwt = false
