-- Updated CID support with official Brazilian CID-10 data (curated selection)
-- This migration creates the CID table and populates it with official Brazilian CID-10 codes

-- Create CID codes table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.cid_codes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  category TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.cid_codes ENABLE ROW LEVEL SECURITY;

-- Clear existing CID codes (if any)
DELETE FROM public.cid_codes;

-- Insert curated selection of common CID-10 codes

-- Chunk 1/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('A00', 'Cólera', 'Infecções'),
('A01', 'Febres tifóide e paratifóide', 'Infecções'),
('A02', 'Outras infecções por Salmonella', 'Infecções'),
('A03', 'Shiguelose', 'Infecções'),
('A04', 'Outras infecções intestinais bacterianas', 'Infecções'),
('A05', 'Outras intoxicações alimentares bacterianas, não classificadas em outra parte', 'Infecções'),
('A06', 'Amebíase', 'Infecções'),
('A07', 'Outras doenças intestinais por protozoários', 'Infecções'),
('A08', 'Infecções intestinais virais, outras e as não especificadas', 'Infecções'),
('A09', 'Diarréia e gastroenterite de origem infecciosa presumível', 'Infecções'),
('A15', 'Tuberculose respiratória, com confirmação bacteriológica e histológica', 'Infecções'),
('A16', 'Tuberculose das vias respiratórias, sem confirmação bacteriológica ou histológica', 'Infecções'),
('A17', 'Tuberculose do sistema nervoso', 'Infecções'),
('A18', 'Tuberculose de outros órgãos', 'Infecções'),
('A19', 'Tuberculose miliar', 'Infecções'),
('A20', 'Peste', 'Infecções'),
('A21', 'Tularemia', 'Infecções'),
('A22', 'Carbúnculo', 'Infecções'),
('A23', 'Brucelose', 'Infecções'),
('A24', 'Mormo e melioidose', 'Infecções'),
('A25', 'Febres transmitidas por mordedura de rato', 'Infecções'),
('A26', 'Erisipelóide', 'Infecções'),
('A27', 'Leptospirose', 'Infecções'),
('A28', 'Outras doenças bacterianas zoonóticas não classificadas em outra parte', 'Infecções'),
('A30', 'Hanseníase [doença de Hansen] [lepra]', 'Infecções'),
('A31', 'Infecções devidas a outras micobactérias', 'Infecções'),
('A32', 'Listeriose [listeríase]', 'Infecções'),
('A33', 'Tétano do recém-nascido [neonatal]', 'Infecções'),
('A34', 'Tétano obstétrico', 'Infecções'),
('A35', 'Outros tipos de tétano', 'Infecções'),
('A36', 'Difteria', 'Infecções'),
('A37', 'Coqueluche', 'Infecções'),
('A38', 'Escarlatina', 'Infecções'),
('A39', 'Infecção meningogócica', 'Infecções'),
('A40', 'Septicemia estreptocócica', 'Infecções'),
('A41', 'Outras septicemias', 'Infecções'),
('A42', 'Actinomicose', 'Infecções'),
('A43', 'Nocardiose', 'Infecções'),
('A44', 'Bartonelose', 'Infecções'),
('A46', 'Erisipela', 'Infecções'),
('A48', 'Outras doenças bacterianas não classificadas em outra parte', 'Infecções'),
('A49', 'Infecção bacteriana de localização não especificada', 'Infecções'),
('A50', 'Sífilis congênita', 'Infecções'),
('A51', 'Sífilis precoce', 'Infecções'),
('A52', 'Sífilis tardia', 'Infecções'),
('A53', 'Outras formas e as não especificadas da sífilis', 'Infecções'),
('A54', 'Infecção gonocócica', 'Infecções'),
('A55', 'Linfogranuloma (venéreo) por clamídia', 'Infecções'),
('A56', 'Outras infecções causadas por clamídias transmitidas por via sexual', 'Infecções'),
('A57', 'Cancro mole', 'Infecções');

-- Chunk 2/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('A60', 'Infecções anogenitais pelo vírus do herpes [herpes simples]', 'Infecções'),
('A65', 'Sífilis não-venérea', 'Infecções'),
('A68', 'Febres recorrentes [Borrelioses]', 'Infecções'),
('A70', 'Infecções causadas por Clamídia psittaci', 'Infecções'),
('A75', 'Tifo exantemático', 'Infecções'),
('A77', 'Febre maculosa [rickettsioses transmitidas por carrapatos]', 'Infecções'),
('A78', 'Febre Q', 'Infecções'),
('A80', 'Poliomielite aguda', 'Infecções'),
('A85', 'Outras encefalites virais, não classificadas em outra parte', 'Infecções'),
('A90', 'Dengue [dengue clássico]', 'Infecções'),
('A91', 'Febre hemorrágica devida ao vírus do dengue', 'Infecções'),
('A92', 'Outras febres virais transmitidas por mosquitos', 'Infecções'),
('A93', 'Outras febres por vírus transmitidas por artrópodes não classificadas em outra parte', 'Infecções'),
('A94', 'Febre viral transmitida por artrópodes, não especificada', 'Infecções'),
('A95', 'Febre amarela', 'Infecções'),
('A96', 'Febre hemorrágica por arenavírus', 'Infecções'),
('A98', 'Outras febres hemorrágicas por vírus, não classificadas em outra parte', 'Infecções'),
('A99', 'Febres hemorrágicas virais não especificadas', 'Infecções'),
('B00', 'Infecções pelo vírus do herpes [herpes simples]', 'Infecções'),
('B05', 'Sarampo', 'Infecções'),
('B15', 'Hepatite aguda A', 'Infecções'),
('B20', 'Doença pelo vírus da imunodeficiência humana [HIV], resultando em doenças infecciosas e parasitárias', 'Infecções'),
('B25', 'Doença por citomegalovírus', 'Infecções'),
('B30', 'Conjuntivite viral', 'Infecções'),
('B35', 'Dermatofitose', 'Infecções'),
('B40', 'Blastomicose', 'Infecções'),
('B45', 'Criptococose', 'Infecções'),
('B50', 'Malária por Plasmodium falciparum', 'Infecções'),
('B55', 'Leishmaniose', 'Infecções'),
('B60', 'Outras doenças devidas a protozoários, não classificadas em outra parte', 'Infecções'),
('B65', 'Esquistossomose [bilharziose] [Schistosomíase]', 'Infecções'),
('B70', 'Difilobotríase e esparganose', 'Infecções'),
('B75', 'Triquinose', 'Infecções'),
('B80', 'Oxiuríase', 'Infecções'),
('B85', 'Pediculose e ftiríase', 'Infecções'),
('B90', 'Seqüelas de tuberculose', 'Infecções'),
('B95', 'Estreptococos e estafilococos como causa de doenças classificadas em outros capítulos', 'Infecções'),
('C00', 'Neoplasia maligna do lábio', 'Neoplasias'),
('C01', 'Neoplasia maligna da base da língua', 'Neoplasias'),
('C02', 'Neoplasia maligna de outras partes e de partes não especificadas da língua', 'Neoplasias'),
('C03', 'Neoplasia maligna da gengiva', 'Neoplasias'),
('C04', 'Neoplasia maligna do assoalho da boca', 'Neoplasias'),
('C05', 'Neoplasia maligna do palato', 'Neoplasias'),
('C06', 'Neoplasia maligna de outras partes e de partes não especificadas da boca', 'Neoplasias'),
('C07', 'Neoplasia maligna da glândula parótida', 'Neoplasias'),
('C08', 'Neoplasia maligna de outras glândulas salivares maiores e as não especificadas', 'Neoplasias'),
('C09', 'Neoplasia maligna da amígdala', 'Neoplasias'),
('C10', 'Neoplasia maligna da orofaringe', 'Neoplasias'),
('C11', 'Neoplasia maligna da nasofaringe', 'Neoplasias'),
('C12', 'Neoplasia maligna do seio piriforme', 'Neoplasias');

-- Chunk 3/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('C13', 'Neoplasia maligna da hipofaringe', 'Neoplasias'),
('C14', 'Neoplasia maligna de outras localizações e de localizações mal definida, do lábio, cavidade oral e faringe', 'Neoplasias'),
('C15', 'Neoplasia maligna do esôfago', 'Neoplasias'),
('C16', 'Neoplasia maligna do estômago', 'Neoplasias'),
('C17', 'Neoplasia maligna do intestino delgado', 'Neoplasias'),
('C18', 'Neoplasia maligna do cólon', 'Neoplasias'),
('C19', 'Neoplasia maligna da junção retossigmóide', 'Neoplasias'),
('C20', 'Neoplasia maligna do reto', 'Neoplasias'),
('C21', 'Neoplasia maligna do ânus e do canal anal', 'Neoplasias'),
('C22', 'Neoplasia maligna do fígado e das vias biliares intra-hepáticas', 'Neoplasias'),
('C23', 'Neoplasia maligna da vesícula biliar', 'Neoplasias'),
('C24', 'Neoplasia maligna de outras partes, e de partes não especificadas das vias biliares', 'Neoplasias'),
('C25', 'Neoplasia maligna do pâncreas', 'Neoplasias'),
('C26', 'Neoplasia maligna de outros órgãos digestivos e de localizações mal definidas no aparelho digestivo', 'Neoplasias'),
('C30', 'Neoplasia maligna da cavidade nasal e do ouvido médio', 'Neoplasias'),
('C31', 'Neoplasia maligna dos seios da face', 'Neoplasias'),
('C32', 'Neoplasia maligna da laringe', 'Neoplasias'),
('C33', 'Neoplasia maligna da traquéia', 'Neoplasias'),
('C34', 'Neoplasia maligna dos brônquios e dos pulmões', 'Neoplasias'),
('C37', 'Neoplasia maligna do timo', 'Neoplasias'),
('C38', 'Neoplasia maligna do coração, mediastino e pleura', 'Neoplasias'),
('C39', 'Neoplasia maligna de outras localizações e de localizações mal definidas do aparelho respiratório e dos órgãos intratorácicos', 'Neoplasias'),
('C40', 'Neoplasia maligna dos ossos e cartilagens articulares dos membros', 'Neoplasias'),
('C41', 'Neoplasia maligna dos ossos e das cartilagens articulares de outras localizações e de localizações não especificadas', 'Neoplasias'),
('C43', 'Melanoma maligno da pele', 'Neoplasias'),
('C44', 'Outras neoplasias malignas da pele', 'Neoplasias'),
('C45', 'Mesotelioma', 'Neoplasias'),
('C46', 'Sarcoma de Kaposi', 'Neoplasias'),
('C47', 'Neoplasia maligna dos nervos periféricos e do sistema nervoso autônomo', 'Neoplasias'),
('C48', 'Neoplasia maligna dos tecidos moles do retroperitônio e do peritônio', 'Neoplasias'),
('C49', 'Neoplasia maligna do tecido conjuntivo e de outros tecidos moles', 'Neoplasias'),
('C50', 'Neoplasia maligna da mama', 'Neoplasias'),
('C51', 'Neoplasia maligna da vulva', 'Neoplasias'),
('C52', 'Neoplasia maligna da vagina', 'Neoplasias'),
('C53', 'Neoplasia maligna do colo do útero', 'Neoplasias'),
('C54', 'Neoplasia maligna do corpo do útero', 'Neoplasias'),
('C55', 'Neoplasia maligna do útero, porção não especificada', 'Neoplasias'),
('C60', 'Neoplasia maligna do pênis', 'Neoplasias'),
('C65', 'Neoplasia maligna da pelve renal', 'Neoplasias'),
('C70', 'Neoplasia maligna das meninges', 'Neoplasias'),
('C75', 'Neoplasia maligna de outras glândulas endócrinas e de estruturas relacionadas', 'Neoplasias'),
('C80', 'Neoplasia maligna, sem especificação de localização', 'Neoplasias'),
('C85', 'Linfoma não-Hodgkin de outros tipos e de tipo não especificado', 'Neoplasias'),
('C90', 'Mieloma múltiplo e neoplasias malignas de plasmócitos', 'Neoplasias'),
('C95', 'Leucemia de tipo celular não especificado', 'Neoplasias'),
('D00', 'Carcinoma in situ da cavidade oral, do esôfago e do estômago', 'Neoplasias'),
('D05', 'Carcinoma in situ da mama', 'Neoplasias'),
('D10', 'Neoplasia benigna da boca e da faringe', 'Neoplasias'),
('D15', 'Neoplasia benigna de outros órgãos intratorácicos e dos não especificados', 'Neoplasias'),
('D20', 'Neoplasia benigna de tecido mole do retroperitônio e do peritônio', 'Neoplasias');

-- Chunk 4/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('D25', 'Leiomioma do útero', 'Neoplasias'),
('D30', 'Neoplasia benigna dos órgãos urinários', 'Neoplasias'),
('D35', 'Neoplasia benigna de outras glândulas endócrinas e das não especificadas', 'Neoplasias'),
('D40', 'Neoplasia de comportamento incerto ou desconhecido dos órgãos genitais masculinos', 'Neoplasias'),
('D45', 'Policitemia vera', 'Neoplasias'),
('D50', 'Anemia por deficiência de ferro', 'Sangue'),
('D51', 'Anemia por deficiência de vitamina B12', 'Sangue'),
('D52', 'Anemia por deficiência de folato', 'Sangue'),
('D53', 'Outras anemias nutricionais', 'Sangue'),
('D55', 'Anemia devida a transtornos enzimáticos', 'Sangue'),
('D56', 'Talassemia', 'Sangue'),
('D57', 'Transtornos falciformes', 'Sangue'),
('D58', 'Outras anemias hemolíticas hereditárias', 'Sangue'),
('D59', 'Anemia hemolítica adquirida', 'Sangue'),
('D60', 'Aplasia pura da série vermelha, adquirida [eritroblastopenia]', 'Sangue'),
('D61', 'Outras anemias aplásticas', 'Sangue'),
('D62', 'Anemia aguda pós-hemorrágica', 'Sangue'),
('D63', 'Anemia em doenças crônicas classificadas em outra parte', 'Sangue'),
('D64', 'Outras anemias', 'Sangue'),
('D65', 'Coagulação intravascular disseminada [síndrome de desfibrinação]', 'Sangue'),
('D66', 'Deficiência hereditária do fator VIII', 'Sangue'),
('D67', 'Deficiência hereditária do fator IX', 'Sangue'),
('D68', 'Outros defeitos da coagulação', 'Sangue'),
('D69', 'Púrpura e outras afecções hemorrágicas', 'Sangue'),
('D70', 'Agranulocitose', 'Sangue'),
('D71', 'Transtornos funcionais dos neutrófilos polimorfonucleares', 'Sangue'),
('D72', 'Outros transtornos dos glóbulos brancos', 'Sangue'),
('D73', 'Doenças do baço', 'Sangue'),
('D74', 'Metemoglobinemia', 'Sangue'),
('D75', 'Outras doenças do sangue e dos órgãos hematopoéticos', 'Sangue'),
('D76', 'Algumas doenças que envolvem o tecido linforreticular e o sistema reticulohistiocítico', 'Sangue'),
('D77', 'Outros transtornos do sangue e dos órgãos hematopoéticos em doenças classificadas em outra parte', 'Sangue'),
('D80', 'Imunodeficiência com predominância de defeitos de anticorpos', 'Sangue'),
('D81', 'Deficiências imunitárias combinadas', 'Sangue'),
('D82', 'Imunodeficiência associada com outros defeitos "major"', 'Sangue'),
('D83', 'Imunodeficiência comum variável', 'Sangue'),
('D84', 'Outras imunodeficiências', 'Sangue'),
('D86', 'Sarcoidose', 'Sangue'),
('D89', 'Outros transtornos que comprometem o mecanismo imunitário não classificados em outra parte', 'Sangue'),
('E00', 'Síndrome de deficiência congênita de iodo', 'Endócrinas'),
('E01', 'Transtornos tireoidianos e afecções associadas, relacionados à deficiência de iodo', 'Endócrinas'),
('E02', 'Hipotireoidismo subclínico por deficiência de iodo', 'Endócrinas'),
('E03', 'Outros hipotireoidismos', 'Endócrinas'),
('E04', 'Outros bócios não-tóxicos', 'Endócrinas'),
('E05', 'Tireotoxicose [hipertireoidismo]', 'Endócrinas'),
('E06', 'Tireoidite', 'Endócrinas'),
('E07', 'Outros transtornos da tireóide', 'Endócrinas'),
('E10', 'Diabetes mellitus insulino-dependente', 'Endócrinas'),
('E11', 'Diabetes mellitus não-insulino-dependente', 'Endócrinas'),
('E12', 'Diabetes mellitus relacionado com a desnutrição', 'Endócrinas');

-- Chunk 5/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('E13', 'Outros tipos especificados de diabetes mellitus', 'Endócrinas'),
('E14', 'Diabetes mellitus não especificado', 'Endócrinas'),
('E15', 'Coma hipoglicêmico não-diabético', 'Endócrinas'),
('E16', 'Outros transtornos da secreção pancreática interna', 'Endócrinas'),
('E20', 'Hipoparatireoidismo', 'Endócrinas'),
('E21', 'Hiperparatireoidismo e outros transtornos da glândula paratireóide', 'Endócrinas'),
('E22', 'Hiperfunção da hipófise', 'Endócrinas'),
('E23', 'Hipofunção e outros transtornos da hipófise', 'Endócrinas'),
('E24', 'Síndrome de Cushing', 'Endócrinas'),
('E25', 'Transtornos adrenogenitais', 'Endócrinas'),
('E26', 'Hiperaldosteronismo', 'Endócrinas'),
('E27', 'Outros transtornos da glândula supra-renal', 'Endócrinas'),
('E28', 'Disfunção ovariana', 'Endócrinas'),
('E29', 'Disfunção testicular', 'Endócrinas'),
('E30', 'Transtornos da puberdade não classificados em outra parte', 'Endócrinas'),
('E31', 'Disfunção poliglandular', 'Endócrinas'),
('E32', 'Doenças do timo', 'Endócrinas'),
('E34', 'Outros transtornos endócrinos', 'Endócrinas'),
('E35', 'Transtornos das glândulas endócrinas em doenças classificadas em outra parte', 'Endócrinas'),
('E40', 'Kwashiorkor', 'Endócrinas'),
('E41', 'Marasmo nutricional', 'Endócrinas'),
('E42', 'Kwashiorkor marasmático', 'Endócrinas'),
('E43', 'Desnutrição protéico-calórica grave não especificada', 'Endócrinas'),
('E44', 'Desnutrição protéico-calórica de graus moderado e leve', 'Endócrinas'),
('E45', 'Atraso do desenvolvimento devido à desnutrição protéico-calórica', 'Endócrinas'),
('E46', 'Desnutrição protéico-calórica não especificada', 'Endócrinas'),
('E50', 'Deficiência de vitamina A', 'Endócrinas'),
('E51', 'Deficiência de tiamina', 'Endócrinas'),
('E52', 'Deficiência de niacina [pelagra]', 'Endócrinas'),
('E53', 'Deficiência de outras vitaminas do grupo B', 'Endócrinas'),
('E54', 'Deficiência de ácido ascórbico', 'Endócrinas'),
('E55', 'Deficiência de vitamina D', 'Endócrinas'),
('E56', 'Outras deficiências vitamínicas', 'Endócrinas'),
('E58', 'Deficiência de cálcio da dieta', 'Endócrinas'),
('E59', 'Deficiência de selênio da dieta', 'Endócrinas'),
('E60', 'Deficiência de zinco da dieta', 'Endócrinas'),
('E61', 'Deficiência de outros elementos nutrientes', 'Endócrinas'),
('E63', 'Outras deficiências nutricionais', 'Endócrinas'),
('E64', 'Seqüelas de desnutrição e de outras deficiências nutricionais', 'Endócrinas'),
('E65', 'Adiposidade localizada', 'Endócrinas'),
('E70', 'Distúrbios do metabolismo de aminoácidos aromáticos', 'Endócrinas'),
('E75', 'Distúrbios do metabolismo de esfingolípides e outros distúrbios de depósito de lípides', 'Endócrinas'),
('E80', 'Distúrbios do metabolismo da porfirina e da bilirrubina', 'Endócrinas'),
('E85', 'Amiloidose', 'Endócrinas'),
('E90', 'Transtornos nutricionais e metabólicos em doenças classificadas em outra parte', 'Endócrinas'),
('F00', 'Demência na doença de Alzheimer', 'Mental'),
('F01', 'Demência vascular', 'Mental'),
('F02', 'Demência em outras doenças classificadas em outra parte', 'Mental'),
('F03', 'Demência não especificada', 'Mental'),
('F04', 'Síndrome amnésica orgânica não induzida pelo álcool ou por outras substâncias psicoativas', 'Mental');

-- Chunk 6/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('F05', 'Delirium não induzido pelo álcool ou por outras substâncias psicoativas', 'Mental'),
('F06', 'Outros transtornos mentais devidos a lesão e disfunção cerebral e a doença física', 'Mental'),
('F07', 'Transtornos de personalidade e do comportamento devidos a doença, a lesão e a disfunção cerebral', 'Mental'),
('F09', 'Transtorno mental orgânico ou sintomático não especificado', 'Mental'),
('F10', 'Transtornos mentais e comportamentais devidos ao uso de álcool', 'Mental'),
('F11', 'Transtornos mentais e comportamentais devidos ao uso de opiáceos', 'Mental'),
('F12', 'Transtornos mentais e comportamentais devidos ao uso de canabinóides', 'Mental'),
('F13', 'Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos', 'Mental'),
('F14', 'Transtornos mentais e comportamentais devidos ao uso da cocaína', 'Mental'),
('F15', 'Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína', 'Mental'),
('F16', 'Transtornos mentais e comportamentais devidos ao uso de alucinógenos', 'Mental'),
('F17', 'Transtornos mentais e comportamentais devidos ao uso de fumo', 'Mental'),
('F18', 'Transtornos mentais e comportamentais devidos ao uso de solventes voláteis', 'Mental'),
('F19', 'Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas', 'Mental'),
('F20', 'Esquizofrenia', 'Mental'),
('F21', 'Transtorno esquizotípico', 'Mental'),
('F22', 'Transtornos delirantes persistentes', 'Mental'),
('F23', 'Transtornos psicóticos agudos e transitórios', 'Mental'),
('F24', 'Transtorno delirante induzido', 'Mental'),
('F25', 'Transtornos esquizoafetivos', 'Mental'),
('F28', 'Outros transtornos psicóticos não-orgânicos', 'Mental'),
('F29', 'Psicose não-orgânica não especificada', 'Mental'),
('F30', 'Episódio maníaco', 'Mental'),
('F31', 'Transtorno afetivo bipolar', 'Mental'),
('F32', 'Episódios depressivos', 'Mental'),
('F33', 'Transtorno depressivo recorrente', 'Mental'),
('F34', 'Transtornos de humor [afetivos] persistentes', 'Mental'),
('F38', 'Outros transtornos do humor [afetivos]', 'Mental'),
('F39', 'Transtorno do humor [afetivo] não especificado', 'Mental'),
('F40', 'Transtornos fóbico-ansiosos', 'Mental'),
('F41', 'Outros transtornos ansiosos', 'Mental'),
('F42', 'Transtorno obsessivo-compulsivo', 'Mental'),
('F43', 'Reações ao "stress" grave e transtornos de adaptação', 'Mental'),
('F44', 'Transtornos dissociativos [de conversão]', 'Mental'),
('F45', 'Transtornos somatoformes', 'Mental'),
('F48', 'Outros transtornos neuróticos', 'Mental'),
('F50', 'Transtornos da alimentação', 'Mental'),
('F51', 'Transtornos não-orgânicos do sono devidos a fatores emocionais', 'Mental'),
('F52', 'Disfunção sexual, não causada por transtorno ou doença orgânica', 'Mental'),
('F53', 'Transtornos mentais e comportamentais associados ao puerpério, não classificados em outra parte', 'Mental'),
('F54', 'Fatores psicológicos ou comportamentais associados a doença ou a transtornos classificados em outra parte', 'Mental'),
('F55', 'Abuso de substâncias que não produzem dependência', 'Mental'),
('F59', 'Síndromes comportamentais associados a transtornos das funções fisiológicas e a fatores físicos, não especificadas', 'Mental'),
('F60', 'Transtornos específicos da personalidade', 'Mental'),
('F61', 'Transtornos mistos da personalidade e outros transtornos da personalidade', 'Mental'),
('F65', 'Transtornos da preferência sexual', 'Mental'),
('F70', 'Retardo mental leve', 'Mental'),
('F80', 'Transtornos específicos do desenvolvimento da fala e da linguagem', 'Mental'),
('F90', 'Transtornos hipercinéticos', 'Mental'),
('F95', 'Tiques', 'Mental');

-- Chunk 7/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('G00', 'Meningite bacteriana não classificada em outra parte', 'Neurológicas'),
('G01', 'Meningite em doenças bacterianas classificadas em outra parte', 'Neurológicas'),
('G02', 'Meningite em outras doenças infecciosas e parasitárias classificadas em outra parte', 'Neurológicas'),
('G03', 'Meningite devida a outras causas e a causas não especificadas', 'Neurológicas'),
('G04', 'Encefalite, mielite e encefalomielite', 'Neurológicas'),
('G05', 'Encefalite, mielite e encefalomielite em doenças classificadas em outra parte', 'Neurológicas'),
('G06', 'Abscesso e granuloma intracranianos e intra-raquidianos', 'Neurológicas'),
('G07', 'Abscesso e granuloma intracranianos e intraspinais em doenças classificadas em outra parte', 'Neurológicas'),
('G08', 'Flebite e tromboflebite intracranianas e intra-raquidianas', 'Neurológicas'),
('G09', 'Seqüelas de doenças inflamatórias do sistema nervoso central', 'Neurológicas'),
('G10', 'Doença de Huntington', 'Neurológicas'),
('G11', 'Ataxia hereditária', 'Neurológicas'),
('G12', 'Atrofia muscular espinal e síndromes correlatas', 'Neurológicas'),
('G13', 'Atrofias sistêmicas que afetam principalmente o sistema nervoso central em doenças classificadas em outra parte', 'Neurológicas'),
('G20', 'Doença de Parkinson', 'Neurológicas'),
('G21', 'Parkinsonismo secundário', 'Neurológicas'),
('G22', 'Parkinsonismo em doenças classificadas em outra parte', 'Neurológicas'),
('G23', 'Outras doenças degenerativas dos gânglios da base', 'Neurológicas'),
('G24', 'Distonia', 'Neurológicas'),
('G25', 'Outras doenças extrapiramidais e transtornos dos movimentos', 'Neurológicas'),
('G26', 'Doenças extrapiramidais e transtornos dos movimentos em doenças classificadas em outra parte', 'Neurológicas'),
('G30', 'Doença de Alzheimer', 'Neurológicas'),
('G31', 'Outras doenças degenerativas do sistema nervoso não classificadas em outra parte', 'Neurológicas'),
('G32', 'Outros transtornos degenerativos do sistema nervoso em doenças classificadas em outra parte', 'Neurológicas'),
('G35', 'Esclerose múltipla', 'Neurológicas'),
('G36', 'Outras desmielinizações disseminadas agudas', 'Neurológicas'),
('G37', 'Outras doenças desmielinizantes do sistema nervoso central', 'Neurológicas'),
('G40', 'Epilepsia', 'Neurológicas'),
('G41', 'Estado de mal epiléptico', 'Neurológicas'),
('G43', 'Enxaqueca', 'Neurológicas'),
('G44', 'Outras síndromes de algias cefálicas', 'Neurológicas'),
('G45', 'Acidentes vasculares cerebrais isquêmicos transitórios e síndromes correlatas', 'Neurológicas'),
('G46', 'Síndromes vasculares cerebrais que ocorrem em doenças cerebrovasculares', 'Neurológicas'),
('G47', 'Distúrbios do sono', 'Neurológicas'),
('G50', 'Transtornos do nervo trigêmeo', 'Neurológicas'),
('G51', 'Transtornos do nervo facial', 'Neurológicas'),
('G52', 'Transtornos de outros nervos cranianos', 'Neurológicas'),
('G53', 'Transtornos dos nervos cranianos em doenças classificadas em outra parte', 'Neurológicas'),
('G54', 'Transtornos das raízes e dos plexos nervosos', 'Neurológicas'),
('G55', 'Compressões das raízes e dos plexos nervosos em doenças classificadas em outra parte', 'Neurológicas'),
('G56', 'Mononeuropatias dos membros superiores', 'Neurológicas'),
('G57', 'Mononeuropatias dos membros inferiores', 'Neurológicas'),
('G58', 'Outras mononeuropatias', 'Neurológicas'),
('G59', 'Mononeuropatias em doenças classificadas em outra parte', 'Neurológicas'),
('G60', 'Neuropatia hereditária e idiopática', 'Neurológicas'),
('G61', 'Polineuropatia inflamatória', 'Neurológicas'),
('G62', 'Outras polineuropatias', 'Neurológicas'),
('G63', 'Polineuropatia em doenças classificadas em outra parte', 'Neurológicas'),
('G64', 'Outros transtornos do sistema nervoso periférico', 'Neurológicas'),
('G70', 'Miastenia gravis e outros transtornos neuromusculares', 'Neurológicas');

-- Chunk 8/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('G80', 'Paralisia cerebral', 'Neurológicas'),
('G90', 'Transtornos do sistema nervoso autônomo', 'Neurológicas'),
('G95', 'Outras doenças da medula espinal', 'Neurológicas'),
('H00', 'Hordéolo e calázio', 'Oftalmológicas'),
('H01', 'Outras inflamações da pálpebra', 'Oftalmológicas'),
('H02', 'Outros transtornos da pálpebra', 'Oftalmológicas'),
('H03', 'Transtornos da pálpebra em doenças classificadas em outras partes', 'Oftalmológicas'),
('H04', 'Transtornos do aparelho lacrimal', 'Oftalmológicas'),
('H05', 'Transtornos da órbita', 'Oftalmológicas'),
('H06', 'Transtornos do aparelho lacrimal e da órbita em doenças classificadas em outra parte', 'Oftalmológicas'),
('H10', 'Conjuntivite', 'Oftalmológicas'),
('H11', 'Outros transtornos da conjuntiva', 'Oftalmológicas'),
('H13', 'Transtornos da conjuntiva em doenças classificadas em outra parte', 'Oftalmológicas'),
('H15', 'Transtornos da esclerótica', 'Oftalmológicas'),
('H16', 'Ceratite', 'Oftalmológicas'),
('H17', 'Cicatrizes e opacidades da córnea', 'Oftalmológicas'),
('H18', 'Outros transtornos da córnea', 'Oftalmológicas'),
('H19', 'Transtorno da esclerótica e da córnea em doenças classificadas em outra parte', 'Oftalmológicas'),
('H20', 'Iridociclite', 'Oftalmológicas'),
('H21', 'Outros transtornos da íris e do corpo ciliar', 'Oftalmológicas'),
('H22', 'Transtornos da íris e do corpo ciliar em doenças classificadas em outra parte', 'Oftalmológicas'),
('H25', 'Catarata senil', 'Oftalmológicas'),
('H26', 'Outras cataratas', 'Oftalmológicas'),
('H27', 'Outros transtornos do cristalino', 'Oftalmológicas'),
('H28', 'Catarata e outros transtornos do cristalino em doenças classificadas em outra parte', 'Oftalmológicas'),
('H30', 'Inflamação coriorretiniana', 'Oftalmológicas'),
('H31', 'Outros transtornos da coróide', 'Oftalmológicas'),
('H32', 'Transtornos coriorretinianos em doenças classificadas em outra parte', 'Oftalmológicas'),
('H33', 'Descolamentos e defeitos da retina', 'Oftalmológicas'),
('H34', 'Oclusões vasculares da retina', 'Oftalmológicas'),
('H35', 'Outros transtornos da retina', 'Oftalmológicas'),
('H36', 'Transtornos da retina em doenças classificadas em outra parte', 'Oftalmológicas'),
('H40', 'Glaucoma', 'Oftalmológicas'),
('H42', 'Glaucoma em doenças classificadas em outra parte', 'Oftalmológicas'),
('H43', 'Transtornos do humor vítreo', 'Oftalmológicas'),
('H44', 'Transtornos do globo ocular', 'Oftalmológicas'),
('H45', 'Transtornos do humor vítreo e do globo ocular em doenças classificadas em outra parte', 'Oftalmológicas'),
('H46', 'Neurite óptica', 'Oftalmológicas'),
('H47', 'Outros transtornos do nervo óptico e das vias ópticas', 'Oftalmológicas'),
('H48', 'Transtornos do nervo óptico [segundo par] e das vias ópticas em doenças classificadas em outra parte', 'Oftalmológicas'),
('H49', 'Estrabismo paralítico', 'Oftalmológicas'),
('H50', 'Outros estrabismos', 'Oftalmológicas'),
('H51', 'Outros transtornos do movimento binocular', 'Oftalmológicas'),
('H52', 'Transtornos da refração e da acomodação', 'Oftalmológicas'),
('H53', 'Distúrbios visuais', 'Oftalmológicas'),
('H54', 'Cegueira e visão subnormal', 'Oftalmológicas'),
('H55', 'Nistagmo e outros movimentos irregulares do olho', 'Oftalmológicas'),
('H57', 'Outros transtornos do olho e anexos', 'Oftalmológicas'),
('H58', 'Outros transtornos do olho e anexos em doenças classificadas em outra parte', 'Oftalmológicas'),
('H59', 'Transtornos do olho e anexos pós-procedimento não classificados em outra parte', 'Oftalmológicas');

-- Chunk 9/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('H60', 'Otite externa', 'Otológicas'),
('H61', 'Outros transtornos do ouvido externo', 'Otológicas'),
('H62', 'Transtornos do ouvido externo em doenças classificadas em outra parte', 'Otológicas'),
('H65', 'Otite média não-supurativa', 'Otológicas'),
('H66', 'Otite média supurativa e as não especificadas', 'Otológicas'),
('H67', 'Otite média em doenças classificadas em outra parte', 'Otológicas'),
('H68', 'Salpingite e obstrução da trompa de Eustáquio', 'Otológicas'),
('H69', 'Outros transtornos da trompa de Eustáquio', 'Otológicas'),
('H70', 'Mastoidite e afecções correlatas', 'Otológicas'),
('H71', 'Colesteatoma do ouvido médio', 'Otológicas'),
('H72', 'Perfuração da membrana do tímpano', 'Otológicas'),
('H73', 'Outros transtornos da membrana do tímpano', 'Otológicas'),
('H74', 'Outros transtornos do ouvido médio e da mastóide', 'Otológicas'),
('H75', 'Outros transtornos do ouvido médio e da mastóide em doenças classificadas em outra parte', 'Otológicas'),
('H80', 'Otosclerose', 'Otológicas'),
('H81', 'Transtornos da função vestibular', 'Otológicas'),
('H82', 'Síndromes vertiginosas em doenças classificadas em outra parte', 'Otológicas'),
('H83', 'Outros transtornos do ouvido interno', 'Otológicas'),
('H90', 'Perda de audição por transtorno de condução e/ou neuro-sensorial', 'Otológicas'),
('H91', 'Outras perdas de audição', 'Otológicas'),
('H92', 'Otalgia e secreção auditiva', 'Otológicas'),
('H93', 'Outros transtornos do ouvido não classificados em outra parte', 'Otológicas'),
('H94', 'Outros transtornos do ouvido em doenças classificadas em outra parte', 'Otológicas'),
('H95', 'Transtornos do ouvido e da apófise mastóide pós-procedimentos, não classificados em outra parte', 'Otológicas'),
('I00', 'Febre reumática sem menção de comprometimento do coração', 'Circulatórias'),
('I01', 'Febre reumática com comprometimento do coração', 'Circulatórias'),
('I02', 'Coréia reumática', 'Circulatórias'),
('I05', 'Doenças reumáticas da valva mitral', 'Circulatórias'),
('I06', 'Doenças reumáticas da valva aórtica', 'Circulatórias'),
('I07', 'Doenças reumáticas da valva tricúspide', 'Circulatórias'),
('I08', 'Doenças de múltiplas valvas', 'Circulatórias'),
('I09', 'Outras doenças reumáticas do coração', 'Circulatórias'),
('I10', 'Hipertensão essencial (primária)', 'Circulatórias'),
('I11', 'Doença cardíaca hipertensiva', 'Circulatórias'),
('I12', 'Doença renal hipertensiva', 'Circulatórias'),
('I13', 'Doença cardíaca e renal hipertensiva', 'Circulatórias'),
('I15', 'Hipertensão secundária', 'Circulatórias'),
('I20', 'Angina pectoris', 'Circulatórias'),
('I21', 'Infarto agudo do miocárdio', 'Circulatórias'),
('I22', 'Infarto do miocárdio recorrente', 'Circulatórias'),
('I23', 'Algumas complicações atuais subseqüentes ao infarto agudo do miocárdio', 'Circulatórias'),
('I24', 'Outras doenças isquêmicas agudas do coração', 'Circulatórias'),
('I25', 'Doença isquêmica crônica do coração', 'Circulatórias'),
('I26', 'Embolia pulmonar', 'Circulatórias'),
('I27', 'Outras formas de doença cardíaca pulmonar', 'Circulatórias'),
('I28', 'Outras doenças dos vasos pulmonares', 'Circulatórias'),
('I30', 'Pericardite aguda', 'Circulatórias'),
('I31', 'Outras doenças do pericárdio', 'Circulatórias'),
('I32', 'Pericardite em doenças classificadas em outra parte', 'Circulatórias'),
('I33', 'Endocardite aguda e subaguda', 'Circulatórias');

-- Chunk 10/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('I34', 'Transtornos não-reumáticos da valva mitral', 'Circulatórias'),
('I35', 'Transtornos não-reumáticos da valva aórtica', 'Circulatórias'),
('I36', 'Transtornos não-reumáticos da valva tricúspide', 'Circulatórias'),
('I37', 'Transtornos da valva pulmonar', 'Circulatórias'),
('I38', 'Endocardite de valva não especificada', 'Circulatórias'),
('I39', 'Endocardite e transtornos valvulares cardíacos em doenças classificadas em outra parte', 'Circulatórias'),
('I40', 'Miocardite aguda', 'Circulatórias'),
('I41', 'Miocardite em doenças classificadas em outra parte', 'Circulatórias'),
('I42', 'Cardiomiopatias', 'Circulatórias'),
('I43', 'Cardiomiopatia em doenças classificadas em outra parte', 'Circulatórias'),
('I44', 'Bloqueio atrioventricular e do ramo esquerdo', 'Circulatórias'),
('I45', 'Outros transtornos de condução', 'Circulatórias'),
('I46', 'Parada cardíaca', 'Circulatórias'),
('I47', 'Taquicardia paroxística', 'Circulatórias'),
('I48', '"Flutter" e fibrilação atrial', 'Circulatórias'),
('I49', 'Outras arritmias cardíacas', 'Circulatórias'),
('I50', 'Insuficiência cardíaca', 'Circulatórias'),
('I51', 'Complicações de cardiopatias e doenças cardíacas mal definidas', 'Circulatórias'),
('I52', 'Outras afecções cardíacas em doenças classificadas em outra parte', 'Circulatórias'),
('I60', 'Hemorragia subaracnóide', 'Circulatórias'),
('I61', 'Hemorragia intracerebral', 'Circulatórias'),
('I62', 'Outras hemorragias intracranianas não-traumáticas', 'Circulatórias'),
('I63', 'Infarto cerebral', 'Circulatórias'),
('I64', 'Acidente vascular cerebral, não especificado como hemorrágico ou isquêmico', 'Circulatórias'),
('I65', 'Oclusão e estenose de artérias pré-cerebrais que não resultam em infarto cerebral', 'Circulatórias'),
('I66', 'Oclusão e estenose de artérias cerebrais que não resultam em infarto cerebral', 'Circulatórias'),
('I70', 'Aterosclerose', 'Circulatórias'),
('I80', 'Flebite e tromboflebite', 'Circulatórias'),
('I85', 'Varizes esofagianas', 'Circulatórias'),
('I95', 'Hipotensão', 'Circulatórias'),
('J00', 'Nasofaringite aguda [resfriado comum]', 'Respiratórias'),
('J01', 'Sinusite aguda', 'Respiratórias'),
('J02', 'Faringite aguda', 'Respiratórias'),
('J03', 'Amigdalite aguda', 'Respiratórias'),
('J04', 'Laringite e traqueíte agudas', 'Respiratórias'),
('J05', 'Laringite obstrutiva aguda [crupe] e epiglotite', 'Respiratórias'),
('J06', 'Infecções agudas das vias aéreas superiores de localizações múltiplas e não especificadas', 'Respiratórias'),
('J09', 'Influenza [gripe] devida a vírus identificado da gripe aviária', 'Respiratórias'),
('J10', 'Influenza devida a outro vírus da influenza [gripe] identificado', 'Respiratórias'),
('J11', 'Influenza [gripe] devida a vírus não identificado', 'Respiratórias'),
('J12', 'Pneumonia viral não classificada em outra parte', 'Respiratórias'),
('J13', 'Pneumonia devida a Streptococcus pneumoniae', 'Respiratórias'),
('J14', 'Pneumonia devida a Haemophilus infuenzae', 'Respiratórias'),
('J15', 'Pneumonia bacteriana não classificada em outra parte', 'Respiratórias'),
('J16', 'Pneumonia devida a outros microorganismos infecciosos especificados não classificados em outra parte', 'Respiratórias'),
('J17', 'Pneumonia em doenças classificadas em outra parte', 'Respiratórias'),
('J18', 'Pneumonia por microorganismo não especificada', 'Respiratórias'),
('J20', 'Bronquite aguda', 'Respiratórias'),
('J21', 'Bronquiolite aguda', 'Respiratórias'),
('J22', 'Infecções agudas não especificada das vias aéreas inferiores', 'Respiratórias');

-- Chunk 11/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('J30', 'Rinite alérgica e vasomotora', 'Respiratórias'),
('J31', 'Rinite, nasofaringite e faringite crônicas', 'Respiratórias'),
('J32', 'Sinusite crônica', 'Respiratórias'),
('J33', 'Pólipo nasal', 'Respiratórias'),
('J34', 'Outros transtornos do nariz e dos seios paranasais', 'Respiratórias'),
('J35', 'Doenças crônicas das amígdalas e das adenóides', 'Respiratórias'),
('J36', 'Abscesso periamigdaliano', 'Respiratórias'),
('J37', 'Laringite e laringotraqueíte crônicas', 'Respiratórias'),
('J38', 'Doenças das cordas vocais e da laringe não classificadas em outra parte', 'Respiratórias'),
('J39', 'Outras doenças das vias aéreas superiores', 'Respiratórias'),
('J40', 'Bronquite não especificada como aguda ou crônica', 'Respiratórias'),
('J41', 'Bronquite crônica simples e a mucopurulenta', 'Respiratórias'),
('J42', 'Bronquite crônica não especificada', 'Respiratórias'),
('J43', 'Enfisema', 'Respiratórias'),
('J44', 'Outras doenças pulmonares obstrutivas crônicas', 'Respiratórias'),
('J45', 'Asma', 'Respiratórias'),
('J46', 'Estado de mal asmático', 'Respiratórias'),
('J47', 'Bronquectasia', 'Respiratórias'),
('J60', 'Pneumoconiose dos mineiros de carvão', 'Respiratórias'),
('J61', 'Pneumoconiose devida a amianto [asbesto] e outras fibras minerais', 'Respiratórias'),
('J62', 'Pneumoconiose devida a poeira que contenham sílica', 'Respiratórias'),
('J63', 'Pneumoconiose devida a outras poeiras inorgânicas', 'Respiratórias'),
('J64', 'Pneumoconiose não especificada', 'Respiratórias'),
('J65', 'Pneumoconiose associada com tuberculose', 'Respiratórias'),
('J66', 'Doenças das vias aéreas devida a poeiras orgânicas específicas', 'Respiratórias'),
('J67', 'Pneumonite de hipersensibilidade devida a poeiras orgânicas', 'Respiratórias'),
('J68', 'Afecções respiratórias devidas a inalação de produtos químicos, gases, fumaças e vapores', 'Respiratórias'),
('J69', 'Pneumonite devida a sólidos e líquidos', 'Respiratórias'),
('J70', 'Afecções respiratórias devida a outros agentes externos', 'Respiratórias'),
('J80', 'Síndrome do desconforto respiratório do adulto', 'Respiratórias'),
('J85', 'Abscesso do pulmão e do mediastino', 'Respiratórias'),
('J90', 'Derrame pleural não classificado em outra parte', 'Respiratórias'),
('J95', 'Afecções respiratórias pós-procedimentos não classificadas em outra parte', 'Respiratórias'),
('K00', 'Distúrbios do desenvolvimento e da erupção dos dentes', 'Digestivas'),
('K01', 'Dentes inclusos e impactados', 'Digestivas'),
('K02', 'Cárie dentária', 'Digestivas'),
('K03', 'Outras doenças dos tecidos dentários duros', 'Digestivas'),
('K04', 'Doenças da polpa e dos tecidos periapicais', 'Digestivas'),
('K05', 'Gengivite e doenças periodontais', 'Digestivas'),
('K06', 'Outros transtornos da gengiva e do rebordo alveolar sem dentes', 'Digestivas'),
('K07', 'Anomalias dentofaciais (inclusive a maloclusão)', 'Digestivas'),
('K08', 'Outros transtornos dos dentes e de suas estruturas de sustentação', 'Digestivas'),
('K09', 'Cistos da região bucal não classificados em outra parte', 'Digestivas'),
('K10', 'Outras doenças dos maxilares', 'Digestivas'),
('K11', 'Doenças das glândulas salivares', 'Digestivas'),
('K12', 'Estomatite e lesões correlatas', 'Digestivas'),
('K13', 'Outras doenças do lábio e da mucosa oral', 'Digestivas'),
('K14', 'Doenças da língua', 'Digestivas'),
('K20', 'Esofagite', 'Digestivas'),
('K21', 'Doença de refluxo gastroesofágico', 'Digestivas');

-- Chunk 12/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('K22', 'Outras doenças do esôfago', 'Digestivas'),
('K23', 'Transtornos do esôfago em doenças classificadas em outra parte', 'Digestivas'),
('K25', 'Úlcera gástrica', 'Digestivas'),
('K26', 'Úlcera duodenal', 'Digestivas'),
('K27', 'Úlcera péptica de localização não especificada', 'Digestivas'),
('K28', 'Úlcera gastrojejunal', 'Digestivas'),
('K29', 'Gastrite e duodenite', 'Digestivas'),
('K30', 'Dispepsia', 'Digestivas'),
('K31', 'Outras doenças do estômago e do duodeno', 'Digestivas'),
('K35', 'Apendicite aguda', 'Digestivas'),
('K36', 'Outras formas de apendicite', 'Digestivas'),
('K37', 'Apendicite, sem outras especificações', 'Digestivas'),
('K38', 'Outras doenças do apêndice', 'Digestivas'),
('K40', 'Hérnia inguinal', 'Digestivas'),
('K41', 'Hérnia femoral', 'Digestivas'),
('K42', 'Hérnia umbilical', 'Digestivas'),
('K43', 'Hérnia ventral', 'Digestivas'),
('K44', 'Hérnia diafragmática', 'Digestivas'),
('K45', 'Outras hérnias abdominais', 'Digestivas'),
('K46', 'Hérnia abdominal não especificada', 'Digestivas'),
('K50', 'Doença de Crohn [enterite regional]', 'Digestivas'),
('K51', 'Colite ulcerativa', 'Digestivas'),
('K52', 'Outras gastroenterites e colites não-infecciosas', 'Digestivas'),
('K55', 'Transtornos vasculares do intestino', 'Digestivas'),
('K56', 'Íleo paralítico e obstrução intestinal sem hérnia', 'Digestivas'),
('K57', 'Doença diverticular do intestino', 'Digestivas'),
('K58', 'Síndrome do cólon irritável', 'Digestivas'),
('K59', 'Outros transtornos funcionais do intestino', 'Digestivas'),
('K60', 'Fissura e fístula das regiões anal e retal', 'Digestivas'),
('K61', 'Abscesso das regiões anal e retal', 'Digestivas'),
('K62', 'Outras doenças do reto e do ânus', 'Digestivas'),
('K63', 'Outras doenças do intestino', 'Digestivas'),
('K65', 'Peritonite', 'Digestivas'),
('K70', 'Doença alcoólica do fígado', 'Digestivas'),
('K75', 'Outras doenças inflamatórias do fígado', 'Digestivas'),
('K80', 'Colelitíase', 'Digestivas'),
('K85', 'Pancreatite aguda', 'Digestivas'),
('K90', 'Má-absorção intestinal', 'Digestivas'),
('L00', 'Síndrome da pele escaldada estafilocócica do recém-nascido', 'Dermatológicas'),
('L01', 'Impetigo', 'Dermatológicas'),
('L02', 'Abscesso cutâneo, furúnculo e antraz', 'Dermatológicas'),
('L03', 'Celulite (Flegmão)', 'Dermatológicas'),
('L04', 'Linfadenite aguda', 'Dermatológicas'),
('L05', 'Cisto pilonidal', 'Dermatológicas'),
('L08', 'Outras infecções localizadas da pele e do tecido subcutâneo', 'Dermatológicas'),
('L10', 'Pênfigo', 'Dermatológicas'),
('L11', 'Outras afecções acantolíticas', 'Dermatológicas'),
('L12', 'Penfigóide', 'Dermatológicas'),
('L13', 'Outras afecções bolhosas', 'Dermatológicas'),
('L14', 'Afecções bolhosas em doenças classificadas em outra parte', 'Dermatológicas');

-- Chunk 13/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('L20', 'Dermatite atópica', 'Dermatológicas'),
('L21', 'Dermatite seborréica', 'Dermatológicas'),
('L22', 'Dermatite das fraldas', 'Dermatológicas'),
('L23', 'Dermatites alérgicas de contato', 'Dermatológicas'),
('L24', 'Dermatites de contato por irritantes', 'Dermatológicas'),
('L25', 'Dermatite de contato não especificada', 'Dermatológicas'),
('L26', 'Dermatite esfoliativa', 'Dermatológicas'),
('L27', 'Dermatite devida a substâncias de uso interno', 'Dermatológicas'),
('L28', 'Líquen simples crônico e prurigo', 'Dermatológicas'),
('L29', 'Prurido', 'Dermatológicas'),
('L30', 'Outras dermatites', 'Dermatológicas'),
('L40', 'Psoríase', 'Dermatológicas'),
('L41', 'Parapsoríase', 'Dermatológicas'),
('L42', 'Pitiríase rósea', 'Dermatológicas'),
('L43', 'Líquen plano', 'Dermatológicas'),
('L44', 'Outras afecções pápulo-descamativas', 'Dermatológicas'),
('L45', 'Afecções pápulo-descamativas em doenças classificadas em outra parte', 'Dermatológicas'),
('L50', 'Urticária', 'Dermatológicas'),
('L51', 'Eritema polimorfo (eritema multiforme)', 'Dermatológicas'),
('L52', 'Eritema nodoso', 'Dermatológicas'),
('L53', 'Outras afecções eritematosas', 'Dermatológicas'),
('L54', 'Eritema em doenças classificadas em outra parte', 'Dermatológicas'),
('L55', 'Queimadura solar', 'Dermatológicas'),
('L56', 'Outras alterações agudas da pele devidas a radiação ultravioleta', 'Dermatológicas'),
('L57', 'Alterações da pele devidas à exposição crônica à radiação não ionizante', 'Dermatológicas'),
('L58', 'Radiodermatite', 'Dermatológicas'),
('L59', 'Outras afecções da pele e do tecido subcutâneo relacionadas com a radiação', 'Dermatológicas'),
('L60', 'Afecções das unhas', 'Dermatológicas'),
('L62', 'Afecções das unhas em doenças classificadas em outra parte', 'Dermatológicas'),
('L63', 'Alopécia areata', 'Dermatológicas'),
('L64', 'Alopécia androgênica', 'Dermatológicas'),
('L65', 'Outras formas não cicatriciais da perda de cabelos ou pêlos', 'Dermatológicas'),
('L66', 'Alopécia cicatricial [perda de cabelos ou pêlos, cicatricial]', 'Dermatológicas'),
('L67', 'Anormalidades da cor e do pedículo dos cabelos e dos pêlos', 'Dermatológicas'),
('L68', 'Hipertricose', 'Dermatológicas'),
('L70', 'Acne', 'Dermatológicas'),
('L71', 'Rosácea', 'Dermatológicas'),
('L72', 'Cistos foliculares da pele e do tecido subcutâneo', 'Dermatológicas'),
('L74', 'Afecções das glândulas sudoríparas écrinas', 'Dermatológicas'),
('L75', 'Afecções das glândulas sudoríparas apócrinas', 'Dermatológicas'),
('L80', 'Vitiligo', 'Dermatológicas'),
('L85', 'Outras formas de espessamento epidérmico', 'Dermatológicas'),
('L90', 'Afecções atróficas da pele', 'Dermatológicas'),
('L95', 'Vasculite limitada a pele não classificadas em outra parte', 'Dermatológicas'),
('M00', 'Artrite piogênica', 'Musculoesqueléticas'),
('M01', 'Infecções diretas da articulação em doenças infecciosas e parasitárias classificadas em outra parte', 'Musculoesqueléticas'),
('M02', 'Artropatias reacionais', 'Musculoesqueléticas'),
('M03', 'Artropatias pós-infecciosas e reacionais em doenças infecciosas classificadas em outra parte', 'Musculoesqueléticas'),
('M05', 'Artrite reumatóide soro-positiva', 'Musculoesqueléticas'),
('M06', 'Outras artrites reumatóides', 'Musculoesqueléticas');

-- Chunk 14/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('M07', 'Artropatias psoriásicas e enteropáticas', 'Musculoesqueléticas'),
('M08', 'Artrite juvenil', 'Musculoesqueléticas'),
('M09', 'Artrite juvenil em doenças classificadas em outra parte', 'Musculoesqueléticas'),
('M10', 'Gota', 'Musculoesqueléticas'),
('M11', 'Outras artropatias por deposição de cristais', 'Musculoesqueléticas'),
('M12', 'Outras artropatias especificadas', 'Musculoesqueléticas'),
('M13', 'Outras artrites', 'Musculoesqueléticas'),
('M14', 'Artropatias em outras doenças classificadas em outra parte', 'Musculoesqueléticas'),
('M15', 'Poliartrose', 'Musculoesqueléticas'),
('M16', 'Coxartrose [artrose do quadril]', 'Musculoesqueléticas'),
('M17', 'Gonartrose [artrose do joelho]', 'Musculoesqueléticas'),
('M18', 'Artrose da primeira articulação carpometacarpiana', 'Musculoesqueléticas'),
('M19', 'Outras artroses', 'Musculoesqueléticas'),
('M20', 'Deformidades adquiridas dos dedos das mãos e dos pés', 'Musculoesqueléticas'),
('M21', 'Outras deformidades adquiridas dos membros', 'Musculoesqueléticas'),
('M22', 'Transtornos da rótula [patela]', 'Musculoesqueléticas'),
('M23', 'Transtornos internos dos joelhos', 'Musculoesqueléticas'),
('M24', 'Outros transtornos articulares específicos', 'Musculoesqueléticas'),
('M25', 'Outros transtornos articulares não classificados em outra parte', 'Musculoesqueléticas'),
('M30', 'Poliarterite nodosa e afecções correlatas', 'Musculoesqueléticas'),
('M31', 'Outras vasculopatias necrotizantes', 'Musculoesqueléticas'),
('M32', 'Lúpus eritematoso disseminado [sistêmico]', 'Musculoesqueléticas'),
('M33', 'Dermatopoliomiosite', 'Musculoesqueléticas'),
('M34', 'Esclerose sistêmica', 'Musculoesqueléticas'),
('M35', 'Outras afecções sistêmicas do tecido conjuntivo', 'Musculoesqueléticas'),
('M36', 'Doenças sistêmicas do tecido conjuntivo em doenças classificadas em outra parte', 'Musculoesqueléticas'),
('M40', 'Cifose e lordose', 'Musculoesqueléticas'),
('M41', 'Escoliose', 'Musculoesqueléticas'),
('M42', 'Osteocondrose da coluna vertebral', 'Musculoesqueléticas'),
('M43', 'Outras dorsopatias deformantes', 'Musculoesqueléticas'),
('M45', 'Espondilite ancilosante', 'Musculoesqueléticas'),
('M46', 'Outras espondilopatias inflamatórias', 'Musculoesqueléticas'),
('M47', 'Espondilose', 'Musculoesqueléticas'),
('M48', 'Outras espondilopatias', 'Musculoesqueléticas'),
('M49', 'Espondilopatias em doenças classificadas em outra parte', 'Musculoesqueléticas'),
('M50', 'Transtornos dos discos cervicais', 'Musculoesqueléticas'),
('M51', 'Outros transtornos de discos intervertebrais', 'Musculoesqueléticas'),
('M53', 'Outras dorsopatias não classificadas em outra parte', 'Musculoesqueléticas'),
('M54', 'Dorsalgia', 'Musculoesqueléticas'),
('M60', 'Miosite', 'Musculoesqueléticas'),
('M61', 'Calcificação e ossificação do músculo', 'Musculoesqueléticas'),
('M62', 'Outros transtornos musculares', 'Musculoesqueléticas'),
('M63', 'Transtornos de músculo em doenças classificadas em outra parte', 'Musculoesqueléticas'),
('M65', 'Sinovite e tenossinovite', 'Musculoesqueléticas'),
('M70', 'Transtornos dos tecidos moles relacionados com o uso, uso excessivo e pressão', 'Musculoesqueléticas'),
('M75', 'Lesões do ombro', 'Musculoesqueléticas'),
('M80', 'Osteoporose com fratura patológica', 'Musculoesqueléticas'),
('M81', 'Osteoporose sem fratura patológica', 'Musculoesqueléticas'),
('M85', 'Outros transtornos da densidade e da estrutura ósseas', 'Musculoesqueléticas'),
('M90', 'Osteopatias em doenças classificadas em outra parte', 'Musculoesqueléticas');

-- Chunk 15/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('M95', 'Outras deformidades adquiridas do sistema osteomuscular e do tecido conjuntivo', 'Musculoesqueléticas'),
('N00', 'Síndrome nefrítica aguda', 'Geniturinárias'),
('N01', 'Síndrome nefrítica rapidamente progressiva', 'Geniturinárias'),
('N02', 'Hematúria recidivante e persistente', 'Geniturinárias'),
('N03', 'Síndrome nefrítica crônica', 'Geniturinárias'),
('N04', 'Síndrome nefrótica', 'Geniturinárias'),
('N05', 'Síndrome nefrítica não especificada', 'Geniturinárias'),
('N06', 'Proteinúria isolada com lesão morfológica especificada', 'Geniturinárias'),
('N07', 'Nefropatia hereditária não classificada em outra parte', 'Geniturinárias'),
('N08', 'Transtornos glomerulares em doenças classificadas em outra parte', 'Geniturinárias'),
('N10', 'Nefrite túbulo-intersticial aguda', 'Geniturinárias'),
('N11', 'Nefrite túbulo-intersticial crônica', 'Geniturinárias'),
('N12', 'Nefrite túbulo-intersticial não especificada se aguda ou crônica', 'Geniturinárias'),
('N13', 'Uropatia obstrutiva e por refluxo', 'Geniturinárias'),
('N14', 'Afecções tubulares e túbulo-intersticiais induzidas por drogas ou metais pesados', 'Geniturinárias'),
('N15', 'Outras doenças renais túbulo-intersticiais', 'Geniturinárias'),
('N16', 'Transtornos renais túbulo-intersticiais em doenças classificadas em outra parte', 'Geniturinárias'),
('N17', 'Insuficiência renal aguda', 'Geniturinárias'),
('N18', 'Insuficiência renal crônica', 'Geniturinárias'),
('N19', 'Insuficiência renal não especificada', 'Geniturinárias'),
('N20', 'Calculose do rim e do ureter', 'Geniturinárias'),
('N21', 'Calculose do trato urinário inferior', 'Geniturinárias'),
('N22', 'Calculose do trato urinário inferior em doenças classificadas em outra parte', 'Geniturinárias'),
('N23', 'Cólica nefrética não especificada', 'Geniturinárias'),
('N25', 'Transtornos resultantes de função renal tubular alterada', 'Geniturinárias'),
('N26', 'Rim contraído, não especificado', 'Geniturinárias'),
('N27', 'Hipoplasia renal de causa desconhecida', 'Geniturinárias'),
('N28', 'Outros transtornos do rim e do ureter não classificado em outra parte', 'Geniturinárias'),
('N29', 'Outros transtornos do rim e do ureter em doenças classificadas em outra parte', 'Geniturinárias'),
('N30', 'Cistite', 'Geniturinárias'),
('N31', 'Disfunções neuromusculares da bexiga não classificados em outra parte', 'Geniturinárias'),
('N32', 'Outros transtornos da bexiga', 'Geniturinárias'),
('N33', 'Transtornos da bexiga em doenças classificadas em outra parte', 'Geniturinárias'),
('N34', 'Uretrite e síndrome uretral', 'Geniturinárias'),
('N35', 'Estenose da uretra', 'Geniturinárias'),
('N36', 'Outros transtornos da uretra', 'Geniturinárias'),
('N37', 'Transtornos da uretra em doenças classificadas em outra parte', 'Geniturinárias'),
('N39', 'Outros transtornos do trato urinário', 'Geniturinárias'),
('N40', 'Hiperplasia da próstata', 'Geniturinárias'),
('N41', 'Doenças inflamatórias da próstata', 'Geniturinárias'),
('N42', 'Outras afecções da próstata', 'Geniturinárias'),
('N43', 'Hidrocele e espermatocele', 'Geniturinárias'),
('N44', 'Torção do testículo', 'Geniturinárias'),
('N45', 'Orquite e epididimite', 'Geniturinárias'),
('N46', 'Infertilidade masculina', 'Geniturinárias'),
('N47', 'Hipertrofia do prepúcio, fimose e parafimose', 'Geniturinárias'),
('N48', 'Outros transtornos do pênis', 'Geniturinárias'),
('N49', 'Transtornos inflamatórios de órgãos genitais masculinos, não classificados em outra parte', 'Geniturinárias'),
('N50', 'Outros transtornos dos órgãos genitais masculinos', 'Geniturinárias'),
('N51', 'Transtornos dos órgãos genitais masculinos em doenças classificadas em outra parte', 'Geniturinárias');

-- Chunk 16/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('N60', 'Displasias mamárias benignas', 'Geniturinárias'),
('N70', 'Salpingite e ooforite', 'Geniturinárias'),
('N75', 'Doenças da glândula de Bartholin', 'Geniturinárias'),
('N80', 'Endometriose', 'Geniturinárias'),
('N85', 'Outros transtornos não-inflamatórios do útero, exceto do colo do útero', 'Geniturinárias'),
('N90', 'Outros transtornos não-inflamatórios da vulva e do períneo', 'Geniturinárias'),
('N94', 'Dor e outras afecções associadas com os órgãos genitais femininos e com o ciclo menstrual', 'Geniturinárias'),
('N95', 'Transtornos da menopausa e da perimenopausa', 'Geniturinárias'),
('O00', 'Gravidez ectópica', 'Obstétricas'),
('O01', 'Mola hidatiforme', 'Obstétricas'),
('O02', 'Outros produtos anormais da concepção', 'Obstétricas'),
('O03', 'Aborto espontâneo', 'Obstétricas'),
('O04', 'Aborto por razões médicas e legais', 'Obstétricas'),
('O05', 'Outros tipos de aborto', 'Obstétricas'),
('O06', 'Aborto não especificado', 'Obstétricas'),
('O07', 'Falha de tentativa de aborto', 'Obstétricas'),
('O08', 'Complicações conseqüentes a aborto e gravidez ectópica ou molar', 'Obstétricas'),
('O10', 'Hipertensão pré-existente complicando a gravidez, o parto e o puerpério', 'Obstétricas'),
('O11', 'Distúrbio hipertensivo pré-existente com proteinúria superposta', 'Obstétricas'),
('O12', 'Edema e proteinúria gestacionais [induzidos pela gravidez], sem hipertensão', 'Obstétricas'),
('O13', 'Hipertensão gestacional [induzida pela gravidez] sem proteinúria significativa', 'Obstétricas'),
('O14', 'Hipertensão gestacional [induzida pela gravidez] com proteinúria significativa', 'Obstétricas'),
('O15', 'Eclâmpsia', 'Obstétricas'),
('O16', 'Hipertensão materna não especificada', 'Obstétricas'),
('O20', 'Hemorragia do início da gravidez', 'Obstétricas'),
('O21', 'Vômitos excessivos na gravidez', 'Obstétricas'),
('O22', 'Complicações venosas na gravidez', 'Obstétricas'),
('O23', 'Infecções do trato geniturinário na gravidez', 'Obstétricas'),
('O24', 'Diabetes mellitus na gravidez', 'Obstétricas'),
('O25', 'Desnutrição na gravidez', 'Obstétricas'),
('O26', 'Assistência materna por outras complicações ligadas predominantemente à gravidez', 'Obstétricas'),
('O28', 'Achados anormais do rastreamento ["screening"] antenatal da mãe', 'Obstétricas'),
('O29', 'Complicações de anestesia administrada durante a gravidez', 'Obstétricas'),
('O30', 'Gestação múltipla', 'Obstétricas'),
('O31', 'Complicações específicas de gestação múltipla', 'Obstétricas'),
('O32', 'Assistência prestada à mãe por motivo de apresentação anormal, conhecida ou suspeitada, do feto', 'Obstétricas'),
('O33', 'Assistência prestada à mãe por uma desproporção conhecida ou suspeita', 'Obstétricas'),
('O34', 'Assistência prestada à mãe por anormalidade, conhecida ou suspeita, dos órgãos pélvicos maternos', 'Obstétricas'),
('O35', 'Assistência prestada à mãe por anormalidade e lesão fetais, conhecidas ou suspeitadas', 'Obstétricas'),
('O36', 'Assistência prestada à mãe por outros problemas fetais conhecidos ou suspeitados', 'Obstétricas'),
('O40', 'Polihidrâmnio', 'Obstétricas'),
('O41', 'Outros transtornos das membranas e do líquido amniótico', 'Obstétricas'),
('O42', 'Ruptura prematura de membranas', 'Obstétricas'),
('O43', 'Transtornos da placenta', 'Obstétricas'),
('O44', 'Placenta prévia', 'Obstétricas'),
('O45', 'Descolamento prematuro da placenta [abruptio placentae]', 'Obstétricas'),
('O46', 'Hemorragia anteparto não classificada em outra parte', 'Obstétricas'),
('O47', 'Falso trabalho de parto', 'Obstétricas'),
('O48', 'Gravidez prolongada', 'Obstétricas'),
('O60', 'Trabalho de parto pré-termo', 'Obstétricas');

-- Chunk 17/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('O61', 'Falha na indução do trabalho de parto', 'Obstétricas'),
('O62', 'Anormalidades da contração uterina', 'Obstétricas'),
('O63', 'Trabalho de parto prolongado', 'Obstétricas'),
('O64', 'Obstrução do trabalho de parto devida à má-posição ou má-apresentação do feto', 'Obstétricas'),
('O65', 'Obstrução do trabalho de parto devida a anormalidade pélvica da mãe', 'Obstétricas'),
('O66', 'Outras formas de obstrução do trabalho de parto', 'Obstétricas'),
('O67', 'Trabalho de parto e parto complicados por hemorragia intraparto não classificados em outra parte', 'Obstétricas'),
('O68', 'Trabalho de parto e parto complicados por sofrimento fetal', 'Obstétricas'),
('O70', 'Laceração do períneo durante o parto', 'Obstétricas'),
('O75', 'Outras complicações do trabalho de parto e do parto não classificadas em outra parte', 'Obstétricas'),
('O80', 'Parto único espontâneo', 'Obstétricas'),
('O85', 'Infecção puerperal', 'Obstétricas'),
('O90', 'Complicações do puerpério não classificadas em outra parte', 'Obstétricas'),
('O95', 'Morte obstétrica de causa não especificada', 'Obstétricas'),
('P00', 'Feto e recém-nascido afetados por afecções maternas, não obrigatoriamente relacionadas com a gravidez atual', 'Perinatais'),
('P01', 'Feto e recém-nascido afetados por complicações maternas da gravidez', 'Perinatais'),
('P02', 'Feto e recém-nascido afetados por complicações da placenta, do cordão umbilical e das membranas', 'Perinatais'),
('P03', 'Feto e recém-nascido afetados por outras complicações do trabalho de parto e do parto', 'Perinatais'),
('P04', 'Feto e recém-nascido afetados por influências nocivas transmitidas ao feto via placenta ou leite materno', 'Perinatais'),
('P05', 'Crescimento fetal retardado e desnutrição fetal', 'Perinatais'),
('P07', 'Transtornos relacionados com a gestação de curta duração e peso baixo ao nascer não classificados em outra parte', 'Perinatais'),
('P08', 'Transtornos relacionados com a gestação prolongada e peso elevado ao nascer', 'Perinatais'),
('P10', 'Laceração intracraniana e hemorragia devidas a traumatismo de parto', 'Perinatais'),
('P11', 'Outros traumatismos de parto do sistema nervoso central', 'Perinatais'),
('P12', 'Lesão do couro cabeludo devida a traumatismo de parto', 'Perinatais'),
('P13', 'Lesões do esqueleto devidas a traumatismo de parto', 'Perinatais'),
('P14', 'Lesões ao nascer do sistema nervoso periférico', 'Perinatais'),
('P15', 'Outros traumatismos de parto', 'Perinatais'),
('P20', 'Hipóxia intra-uterina', 'Perinatais'),
('P21', 'Asfixia ao nascer', 'Perinatais'),
('P22', 'Desconforto (angústia) respiratório(a) do recém-nascido', 'Perinatais'),
('P23', 'Pneumonia congênita', 'Perinatais'),
('P24', 'Síndrome de aspiração neonatal', 'Perinatais'),
('P25', 'Enfisema intersticial e afecções correlatas originadas no período perinatal', 'Perinatais'),
('P26', 'Hemorragia pulmonar originada no período perinatal', 'Perinatais'),
('P27', 'Doença respiratória crônica originada no período perinatal', 'Perinatais'),
('P28', 'Outras afecções respiratórias originadas no período perinatal', 'Perinatais'),
('P29', 'Transtornos cardiovasculares originados no período perinatal', 'Perinatais'),
('P35', 'Doenças virais congênitas', 'Perinatais'),
('P36', 'Septicemia bacteriana do recém-nascido', 'Perinatais'),
('P37', 'Outras doenças infecciosas e parasitárias congênitas', 'Perinatais'),
('P38', 'Onfalite do recém-nascido com ou sem hemorragia leve', 'Perinatais'),
('P39', 'Outras infecções específicas do período perinatal', 'Perinatais'),
('P50', 'Perda sangüínea fetal', 'Perinatais'),
('P51', 'Hemorragia umbilical do recém-nascido', 'Perinatais'),
('P52', 'Hemorragia intracraniana não-traumática do feto e do recém-nascido', 'Perinatais'),
('P53', 'Doença hemorrágica do feto e do recém-nascido', 'Perinatais'),
('P54', 'Outras hemorragias neonatais', 'Perinatais'),
('P55', 'Doença hemolítica do feto e do recém-nascido', 'Perinatais'),
('P56', 'Hidropsia fetal devida a doença hemolítica', 'Perinatais');

-- Chunk 18/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('P57', 'Kernicterus', 'Perinatais'),
('P58', 'Icterícia neonatal devida a outras hemólises excessivas', 'Perinatais'),
('P59', 'Icterícia neonatal devida a outras causas e às não especificadas', 'Perinatais'),
('P60', 'Coagulação intravascular disseminada do feto e do recém-nascido', 'Perinatais'),
('P61', 'Outros transtornos hematológicos perinatais', 'Perinatais'),
('P70', 'Transtornos transitórios do metabolismo dos carboidratos específicos do feto e do recém-nascido', 'Perinatais'),
('P71', 'Transtornos transitórios do metabolismo do cálcio e do magnésio do período neonatal', 'Perinatais'),
('P72', 'Outros transtornos endócrinos transitórios do período neonatal', 'Perinatais'),
('P74', 'Outros distúrbios eletrolíticos e metabólicos transitórios do período neonatal', 'Perinatais'),
('P75', 'Íleo meconial', 'Perinatais'),
('P76', 'Outras obstruções intestinais do recém-nascido', 'Perinatais'),
('P77', 'Enterocolite necrotizante do feto e do recém-nascido', 'Perinatais'),
('P78', 'Outros transtornos do aparelho digestivo do período perinatal', 'Perinatais'),
('P80', 'Hipotermia do recém-nascido', 'Perinatais'),
('P90', 'Convulsões do recém-nascido', 'Perinatais'),
('P95', 'Morte fetal de causa não especificada', 'Perinatais'),
('Q00', 'Anencefalia e malformações similares', 'Congênitas'),
('Q01', 'Encefalocele', 'Congênitas'),
('Q02', 'Microcefalia', 'Congênitas'),
('Q03', 'Hidrocefalia congênita', 'Congênitas'),
('Q04', 'Outras malformações congênitas do cérebro', 'Congênitas'),
('Q05', 'Espinha bífida', 'Congênitas'),
('Q06', 'Outras malformações congênitas da medula espinhal', 'Congênitas'),
('Q07', 'Outras malformações congênitas do sistema nervoso', 'Congênitas'),
('Q10', 'Malformações congênitas das pálpebras, do aparelho lacrimal e da órbita', 'Congênitas'),
('Q11', 'Anoftalmia, microftalmia e macroftalmia', 'Congênitas'),
('Q12', 'Malformações congênitas do cristalino', 'Congênitas'),
('Q13', 'Malformações congênitas da câmara anterior do olho', 'Congênitas'),
('Q14', 'Malformações congênitas da câmara posterior do olho', 'Congênitas'),
('Q15', 'Outras malformações congênitas do olho', 'Congênitas'),
('Q16', 'Malformações congênitas do ouvido causando comprometimento da audição', 'Congênitas'),
('Q17', 'Outras malformações congênitas da orelha', 'Congênitas'),
('Q18', 'Outras malformações congênitas da face e do pescoço', 'Congênitas'),
('Q20', 'Malformações congênitas das câmaras e das comunicações cardíacas', 'Congênitas'),
('Q21', 'Malformações congênitas dos septos cardíacos', 'Congênitas'),
('Q22', 'Malformações congênitas das valvas pulmonar e tricúspide', 'Congênitas'),
('Q23', 'Malformações congênitas das valvas aórtica e mitral', 'Congênitas'),
('Q24', 'Outras malformações congênitas do coração', 'Congênitas'),
('Q25', 'Malformações congênitas das grandes artérias', 'Congênitas'),
('Q26', 'Malformações congênitas das grandes veias', 'Congênitas'),
('Q27', 'Outras malformações congênitas do sistema vascular periférico', 'Congênitas'),
('Q28', 'Outras malformações congênitas do aparelho circulatório', 'Congênitas'),
('Q30', 'Malformação congênita do nariz', 'Congênitas'),
('Q31', 'Malformações congênitas da laringe', 'Congênitas'),
('Q32', 'Malformações congênitas da traquéia e dos brônquios', 'Congênitas'),
('Q33', 'Malformações congênitas do pulmão', 'Congênitas'),
('Q34', 'Outras malformações congênitas do aparelho respiratório', 'Congênitas'),
('Q35', 'Fenda palatina', 'Congênitas'),
('Q36', 'Fenda labial', 'Congênitas'),
('Q37', 'Fenda labial com fenda palatina', 'Congênitas');

-- Chunk 19/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('Q38', 'Outras malformações congênitas da língua, da boca e da faringe', 'Congênitas'),
('Q39', 'Malformações congênitas do esôfago', 'Congênitas'),
('Q40', 'Outras malformações congênitas do trato digestivo superior', 'Congênitas'),
('Q41', 'Ausência, atresia e estenose congênita do intestino delgado', 'Congênitas'),
('Q42', 'Ausência, atresia e estenose congênita do cólon', 'Congênitas'),
('Q43', 'Outras malformações congênitas do intestino', 'Congênitas'),
('Q44', 'Malformações congênitas da vesícula biliar, das vias biliares e do fígado', 'Congênitas'),
('Q45', 'Outras malformações congênitas do aparelho digestivo', 'Congênitas'),
('Q50', 'Malformações congênitas dos ovários, das trompas de Falópio e dos ligamentos largos', 'Congênitas'),
('Q51', 'Malformações congênitas do útero e do colo do útero', 'Congênitas'),
('Q52', 'Outras malformações congênitas dos órgãos genitais femininos', 'Congênitas'),
('Q53', 'Testículo não-descido', 'Congênitas'),
('Q54', 'Hipospádias', 'Congênitas'),
('Q55', 'Outras malformações congênitas dos órgãos genitais masculinos', 'Congênitas'),
('Q56', 'Sexo indeterminado e pseudo-hermafroditismo', 'Congênitas'),
('Q60', 'Agenesia renal e outros defeitos de redução do rim', 'Congênitas'),
('Q65', 'Malformações congênitas do quadril', 'Congênitas'),
('Q70', 'Sindactilia', 'Congênitas'),
('Q75', 'Outras malformações congênitas dos ossos do crânio e da face', 'Congênitas'),
('Q80', 'Ictiose congênita', 'Congênitas'),
('Q85', 'Facomatoses não classificadas em outra parte', 'Congênitas'),
('Q90', 'Síndrome de Down', 'Congênitas'),
('Q95', 'Rearranjos equilibrados e marcadores estruturais, não classificados em outra parte', 'Congênitas'),
('R00', 'Anormalidades do batimento cardíaco', 'Sintomas'),
('R01', 'Sopros e outros ruídos cardíacos', 'Sintomas'),
('R02', 'Gangrena não classificada em outra parte', 'Sintomas'),
('R03', 'Valor anormal da pressão arterial sem diagnóstico', 'Sintomas'),
('R04', 'Hemorragia das vias respiratórias', 'Sintomas'),
('R05', 'Tosse', 'Sintomas'),
('R06', 'Anormalidades da respiração', 'Sintomas'),
('R07', 'Dor de garganta e no peito', 'Sintomas'),
('R09', 'Outros sintomas e sinais relativos aos aparelhos circulatório e respiratório', 'Sintomas'),
('R10', 'Dor abdominal e pélvica', 'Sintomas'),
('R11', 'Náusea e vômitos', 'Sintomas'),
('R12', 'Pirose', 'Sintomas'),
('R13', 'Disfagia', 'Sintomas'),
('R14', 'Flatulência e afecções correlatas', 'Sintomas'),
('R15', 'Incontinência fecal', 'Sintomas'),
('R16', 'Hepatomegalia e esplenomegalia não classificadas em outra parte', 'Sintomas'),
('R17', 'Icterícia não especificada', 'Sintomas'),
('R18', 'Ascite', 'Sintomas'),
('R19', 'Outros sintomas e sinais relativos ao aparelho digestivo e ao abdome', 'Sintomas'),
('R20', 'Distúrbios da sensibilidade cutânea', 'Sintomas'),
('R21', 'Eritema e outras erupções cutâneas não especificadas', 'Sintomas'),
('R22', 'Tumefação, massa ou tumoração localizadas da pele e do tecido subcutâneo', 'Sintomas'),
('R23', 'Outras alterações cutâneas', 'Sintomas'),
('R25', 'Movimentos involuntários anormais', 'Sintomas'),
('R26', 'Anormalidades da marcha e da mobilidade', 'Sintomas'),
('R27', 'Outros distúrbios da coordenação', 'Sintomas'),
('R29', 'Outros sintomas e sinais relativos aos sistemas nervoso e osteomuscular', 'Sintomas');

-- Chunk 20/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('R30', 'Dor associada à micção', 'Sintomas'),
('R31', 'Hematúria não especificada', 'Sintomas'),
('R32', 'Incontinência urinária não especificada', 'Sintomas'),
('R33', 'Retenção urinária', 'Sintomas'),
('R34', 'Anúria e oligúria', 'Sintomas'),
('R35', 'Poliúria', 'Sintomas'),
('R36', 'Secreção uretral', 'Sintomas'),
('R39', 'Outros sintomas e sinais relativos ao aparelho urinário', 'Sintomas'),
('R40', 'Sonolência, estupor e coma', 'Sintomas'),
('R41', 'Outros sintomas e sinais relativos à função cognitiva e à consciência', 'Sintomas'),
('R42', 'Tontura e instabilidade', 'Sintomas'),
('R43', 'Distúrbios do olfato e do paladar', 'Sintomas'),
('R44', 'Outros sintomas e sinais relativos às sensações e às percepções gerais', 'Sintomas'),
('R45', 'Sintomas e sinais relativos ao estado emocional', 'Sintomas'),
('R46', 'Sintomas e sinais relativos à aparência e ao comportamento', 'Sintomas'),
('R47', 'Distúrbios da fala não classificados em outra parte', 'Sintomas'),
('R48', 'Dislexia e outras disfunções simbólicas, não classificadas em outra parte', 'Sintomas'),
('R49', 'Distúrbios da voz', 'Sintomas'),
('R50', 'Febre de origem desconhecida e de outras origens', 'Sintomas'),
('R51', 'Cefaléia', 'Sintomas'),
('R52', 'Dor não classificada em outra parte', 'Sintomas'),
('R53', 'Mal estar, fadiga', 'Sintomas'),
('R54', 'Senilidade', 'Sintomas'),
('R55', 'Síncope e colapso', 'Sintomas'),
('R60', 'Edema não classificado em outra parte', 'Sintomas'),
('R70', 'Velocidade de hemossedimentação elevada e outras anormalidades da viscosidade plasmática', 'Sintomas'),
('R75', 'Evidência laboratorial do vírus da imunodeficiência humana [HIV]', 'Sintomas'),
('R80', 'Proteinúria isolada', 'Sintomas'),
('R85', 'Achados anormais de material proveniente dos órgãos digestivos e da cavidade abdominal', 'Sintomas'),
('R90', 'Resultados anormais de exames para diagnóstico por imagem do sistema nervoso central', 'Sintomas'),
('R95', 'Síndrome da morte súbita na infância', 'Sintomas'),
('S00', 'Traumatismo superficial da cabeça', 'Traumas'),
('S01', 'Ferimento da cabeça', 'Traumas'),
('S02', 'Fratura do crânio e dos ossos da face', 'Traumas'),
('S03', 'Luxação, entorse ou distensão das articulações e dos ligamentos da cabeça', 'Traumas'),
('S04', 'Traumatismo dos nervos cranianos', 'Traumas'),
('S05', 'Traumatismo do olho e da órbita ocular', 'Traumas'),
('S06', 'Traumatismo intracraniano', 'Traumas'),
('S07', 'Lesões por esmagamento da cabeça', 'Traumas'),
('S08', 'Amputação traumática de parte da cabeça', 'Traumas'),
('S09', 'Outros traumatismos da cabeça e os não especificados', 'Traumas'),
('S10', 'Traumatismo superficial do pescoço', 'Traumas'),
('S11', 'Ferimento do pescoço', 'Traumas'),
('S12', 'Fratura do pescoço', 'Traumas'),
('S13', 'Luxação, entorse ou distensão das articulações e dos ligamentos do pescoço', 'Traumas'),
('S14', 'Traumatismo de nervos e da medula espinhal ao nível cervical', 'Traumas'),
('S15', 'Traumatismo dos vasos sangüíneos ao nível do pescoço', 'Traumas'),
('S16', 'Traumatismo de tendões e de músculos do pescoço', 'Traumas'),
('S17', 'Lesões por esmagamento do pescoço', 'Traumas'),
('S18', 'Amputação traumática ao nível do pescoço', 'Traumas');

-- Chunk 21/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('S19', 'Outros traumatismos do pescoço e os não especificados', 'Traumas'),
('S20', 'Traumatismo superficial do tórax', 'Traumas'),
('S21', 'Ferimento do tórax', 'Traumas'),
('S22', 'Fratura de costela(s), esterno e coluna torácica', 'Traumas'),
('S23', 'Luxação, entorse e distensão de articulações e dos ligamentos do tórax', 'Traumas'),
('S24', 'Traumatismos de nervos e da medula espinhal ao nível do tórax', 'Traumas'),
('S25', 'Traumatismo de vasos sangüíneos do tórax', 'Traumas'),
('S26', 'Traumatismo do coração', 'Traumas'),
('S27', 'Traumatismo de outros órgãos intratorácicos e dos não especificados', 'Traumas'),
('S28', 'Lesão por esmagamento do tórax e amputação traumática de parte do tórax', 'Traumas'),
('S29', 'Outros traumatismos do tórax e os não especificados', 'Traumas'),
('S30', 'Traumatismo superficial do abdome, do dorso e da pelve', 'Traumas'),
('S31', 'Ferimento do abdome, do dorso e da pelve', 'Traumas'),
('S32', 'Fratura da coluna lombar e da pelve', 'Traumas'),
('S33', 'Luxação, entorse ou distensão das articulações e dos ligamentos da coluna lombar e da pelve', 'Traumas'),
('S34', 'Traumatismo dos nervos e da medula lombar ao nível do abdome, do dorso e da pelve', 'Traumas'),
('S35', 'Traumatismo de vasos sangüíneos ao nível do abdome, do dorso e da pelve', 'Traumas'),
('S36', 'Traumatismo de órgãos intra-abdominais', 'Traumas'),
('S37', 'Traumatismo do aparelho urinário e de órgãos pélvicos', 'Traumas'),
('S38', 'Lesão por esmagamento e amputação traumática de parte do abdome, do dorso e da pelve', 'Traumas'),
('S39', 'Outros traumatismos e os não especificados do abdome, do dorso e da pelve', 'Traumas'),
('S40', 'Traumatismo superficial do ombro e do braço', 'Traumas'),
('S41', 'Ferimento do ombro e do braço', 'Traumas'),
('S42', 'Fratura do ombro e do braço', 'Traumas'),
('S43', 'Luxação, entorse e distensão das articulações e dos ligamentos da cintura escapular', 'Traumas'),
('S44', 'Traumatismo de nervos ao nível do ombro e do braço', 'Traumas'),
('S45', 'Traumatismo dos vasos sangüíneos ao nível do ombro e do braço', 'Traumas'),
('S46', 'Traumatismo de tendão e músculo ao nível do ombro e do braço', 'Traumas'),
('S47', 'Lesão por esmagamento do ombro e do braço', 'Traumas'),
('S48', 'Amputação traumática do ombro e do braço', 'Traumas'),
('S49', 'Outros traumatismos e os não especificados do ombro e do braço', 'Traumas'),
('S50', 'Traumatismo superficial do cotovelo e do antebraço', 'Traumas'),
('S52', 'Fratura do antebraço', 'Traumas'),
('S55', 'Traumatismo de vasos sangüíneos ao nível do antebraço', 'Traumas'),
('S60', 'Traumatismo superficial do punho e da mão', 'Traumas'),
('S62', 'Fratura ao nível do punho e da mão', 'Traumas'),
('S65', 'Traumatismo de vasos sangüíneos ao nível do punho e da mão', 'Traumas'),
('S70', 'Traumatismo superficial do quadril e da coxa', 'Traumas'),
('S72', 'Fratura do fêmur', 'Traumas'),
('S75', 'Traumatismo de vasos sangüíneos ao nível do quadril e da coxa', 'Traumas'),
('S80', 'Traumatismo superficial da perna', 'Traumas'),
('S82', 'Fratura da perna, incluindo tornozelo', 'Traumas'),
('S85', 'Traumatismo de vasos sangüíneos da perna', 'Traumas'),
('S90', 'Traumatismo superficial do tornozelo e do pé', 'Traumas'),
('S92', 'Fratura do pé (exceto do tornozelo)', 'Traumas'),
('S95', 'Traumatismo de vasos sangüíneos ao nível do tornozelo e do pé', 'Traumas'),
('T00', 'Traumatismos superficiais envolvendo múltiplas regiões do corpo', 'Traumas'),
('T02', 'Fraturas envolvendo múltiplas regiões do corpo', 'Traumas'),
('T05', 'Amputações traumáticas envolvendo múltiplas regiões do corpo', 'Traumas'),
('T08', 'Fratura da coluna, nível não especificado', 'Traumas');

-- Chunk 22/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('T10', 'Fratura do membro superior, nível não especificado', 'Traumas'),
('T12', 'Fratura do membro inferior, nível não especificado', 'Traumas'),
('T15', 'Corpo estranho na parte externa do olho', 'Traumas'),
('T20', 'Queimadura e corrosão da cabeça e pescoço', 'Traumas'),
('T25', 'Queimadura e corrosão do tornozelo e do pé', 'Traumas'),
('T30', 'Queimadura e corrosão, parte não especificada do corpo', 'Traumas'),
('T35', 'Geladura de múltiplas partes do corpo e das não especificadas', 'Traumas'),
('T40', 'Intoxicação por narcóticos e psicodislépticos [alucinógenos]', 'Traumas'),
('T45', 'Intoxicação por substâncias de ação essencialmente sistêmica e substâncias hematológicas, não classificadas em outra parte', 'Traumas'),
('T50', 'Intoxicação por diuréticos e outras drogas, medicamentos e substâncias biológicas e as não especificadas', 'Traumas'),
('T55', 'Efeito tóxico de sabões e detergentes', 'Traumas'),
('T60', 'Efeito tóxico de pesticidas', 'Traumas'),
('T65', 'Efeito tóxico de outras substâncias e as não especificadas', 'Traumas'),
('T70', 'Efeitos da pressão atmosférica e da pressão da água', 'Traumas'),
('T75', 'Efeitos de outras causas externas', 'Traumas'),
('T80', 'Complicações conseqüentes à infusão, transfusão ou injeção terapêutica', 'Traumas'),
('T85', 'Complicações de outros dispositivos protéticos, implantes e enxertos internos', 'Traumas'),
('T90', 'Seqüelas de traumatismo da cabeça', 'Traumas'),
('T95', 'Seqüelas de queimaduras, corrosões e geladuras', 'Traumas'),
('U04', 'Síndrome respiratória aguda grave [severe acute respiratory syndrome SARS]', 'Outros'),
('U80', 'Agente resistente à penicilina e antibióticos relacionados', 'Outros'),
('U81', 'Agente resistente à vancomicina e antibióticos relacionados', 'Outros'),
('U88', 'Agente resistente a múltiplos antibióticos', 'Outros'),
('U89', 'Agente resistente a outros antibióticos e a antibióticos não especificados', 'Outros'),
('U99', 'CID 10ª Revisão não disponível', 'Outros'),
('V01', 'Pedestre traumatizado em colisão com um veículo a pedal', 'Causas Externas'),
('V02', 'Pedestre traumatizado em colisão com um veículo a motor de duas ou três rodas', 'Causas Externas'),
('V03', 'Pedestre traumatizado em colisão com um automóvel [carro], "pick up" ou caminhonete', 'Causas Externas'),
('V04', 'Pedestre traumatizado em colisão com um veículo de transporte pesado ou com um ônibus', 'Causas Externas'),
('V05', 'Pedestre traumatizado em colisão com trem [comboio] ou um veículo ferroviário', 'Causas Externas'),
('V06', 'Pedestre traumatizado em colisão com outro veículo não-motorizado', 'Causas Externas'),
('V09', 'Pedestre traumatizado em outros acidentes de transporte e em acidentes de transporte não especificados', 'Causas Externas'),
('V10', 'Ciclista traumatizado em colisão com um pedestre ou um animal', 'Causas Externas'),
('V11', 'Ciclista traumatizado em colisão com outro veículo a pedal', 'Causas Externas'),
('V12', 'Ciclista traumatizado em colisão com um veículo a motor de duas ou três rodas', 'Causas Externas'),
('V13', 'Ciclista traumatizado em colisão com um automóvel, "pick up" ou caminhonete', 'Causas Externas'),
('V14', 'Ciclista traumatizado em colisão com um veículo de transporte pesado ou um ônibus', 'Causas Externas'),
('V15', 'Ciclista traumatizado em colisão com um trem ou um veículo ferroviário', 'Causas Externas'),
('V16', 'Ciclista traumatizado em colisão com outro veículo não-motorizado', 'Causas Externas'),
('V17', 'Ciclista traumatizado em colisão com um objeto fixo ou parado', 'Causas Externas'),
('V18', 'Ciclista traumatizado em um acidente de transporte sem colisão', 'Causas Externas'),
('V19', 'Ciclista traumatizado em outros acidentes de transporte e em acidentes de transporte não especificados', 'Causas Externas'),
('V20', 'Motociclista traumatizado em colisão com um pedestre ou um animal', 'Causas Externas'),
('V21', 'Motociclista traumatizado em colisão com um veículo a pedal', 'Causas Externas'),
('V22', 'Motociclista traumatizado em colisão com um veículo a motor de duas ou três rodas', 'Causas Externas'),
('V23', 'Motociclista traumatizado em colisão com um automóvel [carro], "pick up" ou caminhonete', 'Causas Externas'),
('V24', 'Motociclista traumatizado em colisão com um veículo de transporte pesado ou um ônibus', 'Causas Externas'),
('V25', 'Motociclista traumatizado em colisão com um trem ou um veículo ferroviário', 'Causas Externas'),
('V26', 'Motociclista traumatizado em colisão com outro veículo não-motorizado', 'Causas Externas'),
('V27', 'Motociclista traumatizado em colisão com um objeto fixo ou parado', 'Causas Externas');

-- Chunk 23/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('V28', 'Motociclista traumatizado em um acidente de transporte sem colisão', 'Causas Externas'),
('V29', 'Motociclista traumatizado em outros acidentes de transporte e em acidentes de transporte não especificados', 'Causas Externas'),
('V30', 'Ocupante de um triciclo motorizado traumatizado em colisão com um pedestre ou um animal', 'Causas Externas'),
('V31', 'Ocupante de um triciclo motorizado traumatizado em colisão com um veículo a pedal', 'Causas Externas'),
('V32', 'Ocupante de um triciclo motorizado traumatizado em colisão com outro veículo a motor de duas ou três rodas', 'Causas Externas'),
('V33', 'Ocupante de um triciclo motorizado traumatizado em colisão com um automóvel, "pick up" ou caminhonete', 'Causas Externas'),
('V34', 'Ocupante de um triciclo motorizado traumatizado em colisão com um veículo de transporte pesado ou um ônibus', 'Causas Externas'),
('V35', 'Ocupante de um triciclo motorizado traumatizado em colisão com um trem [comboio] ou um veículo ferroviário', 'Causas Externas'),
('V36', 'Ocupante de um triciclo motorizado traumatizado em colisão com outro veículo não-motorizado', 'Causas Externas'),
('V37', 'Ocupante de um triciclo motorizado traumatizado em colisão com um objeto fixo ou parado', 'Causas Externas'),
('V38', 'Ocupante de um triciclo motorizado traumatizado em um acidente de transporte sem colisão', 'Causas Externas'),
('V39', 'Ocupante de um triciclo motorizado traumatizado em outros acidentes de transporte e em acidentes de transporte não especificados', 'Causas Externas'),
('V40', 'Ocupante de um automóvel [carro] traumatizado em colisão com um pedestre ou um animal', 'Causas Externas'),
('V41', 'Ocupante de um automóvel [carro] traumatizado em colisão com um veículo a pedal', 'Causas Externas'),
('V42', 'Ocupante de um automóvel [carro] traumatizado em colisão com outro veículo a motor de duas ou três rodas', 'Causas Externas'),
('V43', 'Ocupante de um automóvel [carro] traumatizado em colisão com um automóvel [carro], "pick up" ou caminhonete', 'Causas Externas'),
('V44', 'Ocupante de um automóvel [carro] traumatizado em colisão com um veículo de transporte pesado ou um ônibus', 'Causas Externas'),
('V45', 'Ocupante de um automóvel [carro] traumatizado em colisão com um trem [comboio] ou um veículo ferroviário', 'Causas Externas'),
('V46', 'Ocupante de um automóvel [carro] traumatizado em colisão com outro veículo não-motorizado', 'Causas Externas'),
('V47', 'Ocupante de um automóvel [carro] traumatizado em colisão com um objeto fixo ou parado', 'Causas Externas'),
('V48', 'Ocupante de um automóvel [carro] traumatizado em um acidente de transporte sem colisão', 'Causas Externas'),
('V49', 'Ocupante de um automóvel [carro] traumatizado em outro acidentes de transporte e em acidentes de transporte não especificados', 'Causas Externas'),
('V50', 'Ocupante de uma caminhonete traumatizado em colisão com um pedestre ou um animal', 'Causas Externas'),
('V51', 'Ocupante de uma caminhonete traumatizado em colisão com um veículo a pedal', 'Causas Externas'),
('V52', 'Ocupante de uma caminhonete traumatizado em colisão com veículo a motor de duas ou três rodas', 'Causas Externas'),
('V55', 'Ocupante de uma caminhonete traumatizado em colisão com um trem [comboio] ou veículo ferroviário', 'Causas Externas'),
('V60', 'Ocupante de um veículo de transporte pesado traumatizado em colisão com um pedestre ou um animal', 'Causas Externas'),
('V65', 'Ocupante de um veículo de transporte pesado traumatizado em colisão com um trem [comboio] ou um veículo ferroviário', 'Causas Externas'),
('V70', 'Ocupante de um ônibus traumatizado em colisão com um pedestre ou um animal', 'Causas Externas'),
('V75', 'Ocupante de um ônibus traumatizado em colisão com um trem [comboio] ou um veículo ferroviário', 'Causas Externas'),
('V80', 'Pessoa montada em animal ou ocupante de um veículo a tração animal traumatizado em um acidente de transporte', 'Causas Externas'),
('V85', 'Ocupante de um veículo a motor especial de construções traumatizado em um acidente de transporte', 'Causas Externas'),
('V90', 'Acidente com embarcação causando afogamento e submersão', 'Causas Externas'),
('V95', 'Acidente de aeronave a motor causando traumatismo ao ocupante', 'Causas Externas'),
('W00', 'Queda no mesmo nível envolvendo gelo e neve', 'Causas Externas'),
('W05', 'Queda envolvendo uma cadeira de rodas', 'Causas Externas'),
('W10', 'Queda em ou de escadas ou degraus', 'Causas Externas'),
('W15', 'Queda de penhasco', 'Causas Externas'),
('W20', 'Impacto causado por objeto lançado, projetado ou em queda', 'Causas Externas'),
('W24', 'Contato com elevadores e instrumentos de transmissão, não classificados em outra parte', 'Causas Externas'),
('W25', 'Contato com vidro cortante', 'Causas Externas'),
('W30', 'Contato com maquinaria agrícola', 'Causas Externas'),
('W35', 'Explosão ou ruptura de caldeira', 'Causas Externas'),
('W40', 'Explosão de outros materiais', 'Causas Externas'),
('W45', 'Penetração de corpo ou objeto estranho através da pele', 'Causas Externas'),
('W50', 'Golpe, pancada, pontapé, mordedura ou escoriação infligidos por outra pessoa', 'Causas Externas'),
('W55', 'Mordedura ou golpe provocado por outros animais mamíferos', 'Causas Externas'),
('W60', 'Contato com espinhos de plantas ou com folhas aguçadas', 'Causas Externas'),
('W65', 'Afogamento e submersão durante banho em banheira', 'Causas Externas'),
('W70', 'Afogamento e submersão conseqüentes a queda dentro de águas naturais', 'Causas Externas');

-- Chunk 24/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('W75', 'Sufocação e estrangulamento acidental na cama', 'Causas Externas'),
('W80', 'Inalação e ingestão de outros objetos causando obstrução do trato respiratório', 'Causas Externas'),
('W85', 'Exposição a linhas de transmissão de corrente elétrica', 'Causas Externas'),
('W90', 'Exposição a outros tipos de radiação não-ionizante', 'Causas Externas'),
('X00', 'Exposição a fogo não-controlado em um edifício ou outro tipo de construção', 'Causas Externas'),
('X05', 'Exposição a combustão de roupa de dormir', 'Causas Externas'),
('X10', 'Contato com bebidas, alimentos, gordura e óleo de cozinha quentes', 'Causas Externas'),
('X15', 'Contato com aparelhos domésticos quentes', 'Causas Externas'),
('X16', 'Contato com aquecedores, radiadores e tubulação', 'Causas Externas'),
('X20', 'Contato com serpentes e lagartos venenosos', 'Causas Externas'),
('X25', 'Contato com outros artrópodes venenosos', 'Causas Externas'),
('X30', 'Exposição a calor natural excessivo', 'Causas Externas'),
('X35', 'Vítima de erupção vulcânica', 'Causas Externas'),
('X40', 'Envenenamento [intoxicação] acidental por e exposição a analgésicos, antipiréticos e anti-reumáticos, não-opiáceos', 'Causas Externas'),
('X45', 'Envenenamento [intoxicação] acidental por e exposição ao álcool', 'Causas Externas'),
('X50', 'Excesso de exercícios e movimentos vigorosos ou repetitivos', 'Causas Externas'),
('X60', 'Auto-intoxicação por e exposição, intencional, a analgésicos, antipiréticos e anti-reumáticos, não-opiáceos', 'Causas Externas'),
('X65', 'Auto-intoxicação voluntária por álcool', 'Causas Externas'),
('X70', 'Lesão autoprovocada intencionalmente por enforcamento, estrangulamento e sufocação', 'Causas Externas'),
('X75', 'Lesão autoprovocada intencionalmente por dispositivos explosivos', 'Causas Externas'),
('X80', 'Lesão autoprovocada intencionalmente por precipitação de um lugar elevado', 'Causas Externas'),
('X85', 'Agressão por meio de drogas, medicamentos e substâncias biológicas', 'Causas Externas'),
('X90', 'Agressão por meio de produtos químicos e substâncias nocivas não especificados', 'Causas Externas'),
('X95', 'Agressão por meio de disparo de outra arma de fogo ou de arma não especificada', 'Causas Externas'),
('Y00', 'Agressão por meio de um objeto contundente', 'Causas Externas'),
('Y05', 'Agressão sexual por meio de força física', 'Causas Externas'),
('Y10', 'Envenenamento [intoxicação] por e exposição a analgésicos, antipiréticos e anti-reumáticos não-opiáceos, intenção não determinada', 'Causas Externas'),
('Y15', 'Envenenamento [intoxicação] por e exposição ao álcool, intenção não determinada', 'Causas Externas'),
('Y20', 'Enforcamento, estrangulamento e sufocação, intenção não determinada', 'Causas Externas'),
('Y25', 'Contato com material explosivo, intenção não determinada', 'Causas Externas'),
('Y30', 'Queda, salto ou empurrado de um lugar elevado, intenção não determinada', 'Causas Externas'),
('Y35', 'Intervenção legal', 'Causas Externas'),
('Y40', 'Efeitos adversos de antibióticos sistêmicos', 'Causas Externas'),
('Y45', 'Efeitos adversos de substâncias analgésicas, antipiréticas e antiinflamatórias', 'Causas Externas'),
('Y50', 'Efeitos adversos de estimulantes do sistema nervoso central, não classificados em outra parte', 'Causas Externas'),
('Y55', 'Efeitos adversos de substâncias que atuam primariamente sobre os músculos lisos e esqueléticos e sobre o aparelho respiratório', 'Causas Externas'),
('Y60', 'Corte, punção, perfuração ou hemorragia acidentais durante a prestação de cuidados médicos ou cirúrgicos', 'Causas Externas'),
('Y65', 'Outros acidentes durante a prestação de cuidados médicos e cirúrgicos', 'Causas Externas'),
('Y70', 'Dispositivos (aparelhos) de anestesiologia, associados a incidentes adversos', 'Causas Externas'),
('Y75', 'Dispositivos (aparelhos) utilizados em neurologia, associados a incidentes adversos', 'Causas Externas'),
('Y80', 'Dispositivos (aparelhos) utilizados em medicina física (fisiatria), associado a incidentes adversos', 'Causas Externas'),
('Y85', 'Seqüelas de acidentes de transporte', 'Causas Externas'),
('Y90', 'Evidência de alcoolismo determinada por taxas de alcoolemia', 'Causas Externas'),
('Y95', 'Circunstância relativa as condições nosocomiais (hospitalares)', 'Causas Externas'),
('Z00', 'Exame geral e investigação de pessoas sem queixas ou diagnóstico relatado', 'Prevenção'),
('Z01', 'Outros exames e investigações especiais de pessoas sem queixa ou diagnóstico relatado', 'Prevenção'),
('Z02', 'Exame médico e consulta com finalidades administrativas', 'Prevenção'),
('Z03', 'Observação e avaliação médica por doenças e afecções suspeitas', 'Prevenção'),
('Z04', 'Exame e observação por outras razões', 'Prevenção'),
('Z08', 'Exame de seguimento após tratamento por neoplasia maligna', 'Prevenção');

-- Chunk 25/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('Z09', 'Exame de seguimento após tratamento de outras afecções que não neoplasias malignas', 'Prevenção'),
('Z10', 'Exame geral de rotina ("check up") de uma subpopulação definida', 'Prevenção'),
('Z11', 'Exame especial de rastreamento ("screening") de doenças infecciosas e parasitárias', 'Prevenção'),
('Z12', 'Exame especial de rastreamento ("screening") de neoplasias', 'Prevenção'),
('Z13', 'Exame especial de rastreamento ("screening") de outros transtornos e doenças', 'Prevenção'),
('Z20', 'Contato com e exposição a doenças transmissíveis', 'Prevenção'),
('Z21', 'Estado de infecção assintomática pelo vírus da imunodeficiência humana [HIV]', 'Prevenção'),
('Z22', 'Portador de doença infecciosa', 'Prevenção'),
('Z23', 'Necessidade de imunização contra uma única doença bacteriana', 'Prevenção'),
('Z24', 'Necessidade de imunização contra algumas doenças virais únicas', 'Prevenção'),
('Z25', 'Necessidade de imunização contra outras doenças virais únicas', 'Prevenção'),
('Z26', 'Necessidade de imunização contra outras doenças infecciosas únicas', 'Prevenção'),
('Z27', 'Necessidade de imunização associada contra combinações de doenças infecciosas', 'Prevenção'),
('Z28', 'Imunização não realizada', 'Prevenção'),
('Z29', 'Necessidade de outras medidas profiláticas', 'Prevenção'),
('Z30', 'Anticoncepção', 'Prevenção'),
('Z31', 'Medidas de procriação', 'Prevenção'),
('Z32', 'Exame ou teste de gravidez', 'Prevenção'),
('Z33', 'Gravidez como achado casual', 'Prevenção'),
('Z34', 'Supervisão de gravidez normal', 'Prevenção'),
('Z35', 'Supervisão de gravidez de alto risco', 'Prevenção'),
('Z36', 'Rastreamento ("screening") pré-natal', 'Prevenção'),
('Z37', 'Resultado do parto', 'Prevenção'),
('Z38', 'Nascidos vivos [nado-vivos] segundo o local de nascimento', 'Prevenção'),
('Z39', 'Assistência e exame pós-natal', 'Prevenção'),
('Z40', 'Cirurgia profilática', 'Prevenção'),
('Z41', 'Procedimentos para outros propósitos exceto cuidados de saúde', 'Prevenção'),
('Z42', 'Seguimento envolvendo cirurgia plástica', 'Prevenção'),
('Z43', 'Atenção a orifícios artificiais', 'Prevenção'),
('Z44', 'Colocação e ajustamento de aparelhos de prótese externa', 'Prevenção'),
('Z45', 'Ajustamento e manuseio de dispositivo implantado', 'Prevenção'),
('Z46', 'Colocação e ajustamento de outros aparelhos', 'Prevenção'),
('Z47', 'Outros cuidados de seguimento ortopédico', 'Prevenção'),
('Z48', 'Outro seguimento cirúrgico', 'Prevenção'),
('Z49', 'Cuidados envolvendo diálise', 'Prevenção'),
('Z50', 'Cuidados envolvendo o uso de procedimentos de reabilitação', 'Prevenção'),
('Z51', 'Outros cuidados médicos', 'Prevenção'),
('Z52', 'Doadores de órgãos e tecidos', 'Prevenção'),
('Z53', 'Pessoas em contato com serviços de saúde para procedimentos específicos não realizados', 'Prevenção'),
('Z54', 'Convalescença', 'Prevenção'),
('Z55', 'Problemas relacionados com a educação e com a alfabetização', 'Prevenção'),
('Z56', 'Problemas relacionados com o emprego e com o desemprego', 'Prevenção'),
('Z57', 'Exposição ocupacional a fatores de risco', 'Prevenção'),
('Z58', 'Problemas relacionados com o ambiente físico', 'Prevenção'),
('Z60', 'Problemas relacionados com o meio social', 'Prevenção'),
('Z65', 'Problemas relacionados com outras circunstâncias psicossociais', 'Prevenção'),
('Z70', 'Aconselhamento relativo às atitudes, comportamento e orientação em matéria de sexualidade', 'Prevenção'),
('Z75', 'Problemas relacionados com as facilidades médicas e outros cuidados de saúde', 'Prevenção'),
('Z80', 'História familiar de neoplasia maligna', 'Prevenção'),
('Z85', 'História pessoal de neoplasia maligna', 'Prevenção');

-- Chunk 26/26
INSERT INTO public.cid_codes (code, description, category) VALUES
('Z90', 'Ausência adquirida de órgãos não classificados em outra parte', 'Prevenção'),
('Z95', 'Presença de implantes e enxertos cardíacos e vasculares', 'Prevenção');

-- Update the updated_at timestamp
UPDATE public.cid_codes SET updated_at = NOW();
